package org.rsmod.content.skills.thieving

internal data class PickpocketTarget(
    val npcs: List<String>,
    val displayName: String,
    val level: Int,
    val xp: Double,
    val pouch: String? = null,
    val coins: Int = 0,
    val rewards: List<ThievingReward> = emptyList(),
    val lowChance: Int,
    val highChance: Int,
    val failDamage: Int = 1,
)

internal data class StallTarget(
    val locIds: IntArray,
    val displayName: String,
    val level: Int,
    val xp: Double,
    val rewards: List<ThievingReward>,
    val emptyLocId: Int? = null,
    val respawnTicks: Int = 50,
)

internal data class ChestTarget(
    val locIds: IntArray,
    val displayName: String,
    val level: Int,
    val xp: Double,
    val rewards: List<ThievingReward>,
    val openLocId: Int? = null,
    val respawnTicks: Int = 100,
)

internal data class ThievingReward(
    val obj: String,
    val count: Int = 1,
)

internal object ThievingDefinitions {
    const val COINS = "obj.coins"
    private const val EMPTY_MARKET_STALL = 6573

    val pickpocketTargets =
        listOf(
            PickpocketTarget(
                npcs =
                    listOf(
                        "npc.man",
                        "npc.man2",
                        "npc.man3",
                        "npc.man4",
                        "npc.man_indoor",
                        "npc.woman",
                        "npc.woman2",
                        "npc.woman3",
                        "npc.woman4",
                    ),
                displayName = "citizen",
                level = 1,
                xp = 8.0,
                pouch = "obj.pickpocket_coin_pouch_citizen",
                coins = 3,
                lowChance = 120,
                highChance = 255,
            ),
            PickpocketTarget(
                npcs = listOf("npc.farmer1", "npc.farmer2", "npc.farmer3", "npc.farmer1_f", "npc.farmer2_f", "npc.farmer3_f"),
                displayName = "farmer",
                level = 10,
                xp = 14.5,
                pouch = "obj.pickpocket_coin_pouch_farmer",
                coins = 9,
                lowChance = 105,
                highChance = 245,
            ),
            PickpocketTarget(
                npcs = listOf("npc.favour_male_ham_civilian", "npc.favour_female_ham_civilian"),
                displayName = "H.A.M. member",
                level = 15,
                xp = 18.5,
                pouch = "obj.pickpocket_coin_pouch_ham",
                coins = 12,
                lowChance = 96,
                highChance = 238,
            ),
            PickpocketTarget(
                npcs = listOf("npc.warrior_woman", "npc.warrior_woman_variant01", "npc.warrior_woman_variant02", "npc.al_kharid_warrior"),
                displayName = "warrior",
                level = 25,
                xp = 26.0,
                pouch = "obj.pickpocket_coin_pouch_warrior",
                coins = 18,
                lowChance = 82,
                highChance = 230,
                failDamage = 2,
            ),
            PickpocketTarget(
                npcs = listOf("npc.rogue", "npc.wilderness_rogue"),
                displayName = "rogue",
                level = 32,
                xp = 35.5,
                pouch = "obj.pickpocket_coin_pouch_rogue",
                coins = 25,
                lowChance = 72,
                highChance = 220,
                failDamage = 2,
            ),
            PickpocketTarget(
                npcs =
                    listOf(
                        "npc.cave_goblin",
                        "npc.cave_goblin2",
                        "npc.cave_goblin3",
                        "npc.cave_goblin4",
                        "npc.cave_goblin_miner",
                        "npc.cave_goblin_miner2",
                        "npc.cave_goblin_miner3",
                        "npc.cave_goblin_miner4",
                    ),
                displayName = "cave goblin",
                level = 36,
                xp = 40.0,
                pouch = "obj.pickpocket_coin_pouch_cavegoblin",
                coins = 10,
                lowChance = 68,
                highChance = 215,
                failDamage = 2,
            ),
            PickpocketTarget(
                npcs = listOf("npc.master_farmer_1", "npc.master_farmer_1_f", "npc.master_farmer_2", "npc.master_farmer_2_f"),
                displayName = "master farmer",
                level = 38,
                xp = 43.0,
                rewards =
                    listOf(
                        ThievingReward("obj.potato_seed", 4),
                        ThievingReward("obj.onion_seed", 3),
                        ThievingReward("obj.cabbage_seed", 3),
                        ThievingReward("obj.tomato_seed", 2),
                        ThievingReward("obj.sweetcorn_seed", 2),
                        ThievingReward("obj.strawberry_seed"),
                        ThievingReward("obj.watermelon_seed"),
                        ThievingReward("obj.limpwurt_seed"),
                        ThievingReward("obj.ranarr_seed"),
                        ThievingReward("obj.snapdragon_seed"),
                        ThievingReward("obj.torstol_seed"),
                    ),
                lowChance = 64,
                highChance = 212,
                failDamage = 3,
            ),
            PickpocketTarget(
                npcs = listOf("npc.guard1", "npc.guard1_f", "npc.guard1_variant01", "npc.guard1_f_variant01", "npc.ardougne_guard", "npc.ardougne_guard_f"),
                displayName = "guard",
                level = 40,
                xp = 46.8,
                pouch = "obj.pickpocket_coin_pouch_guard",
                coins = 30,
                lowChance = 62,
                highChance = 210,
                failDamage = 2,
            ),
            PickpocketTarget(
                npcs =
                    listOf(
                        "npc.viking_man",
                        "npc.viking_man2",
                        "npc.viking_man3",
                        "npc.viking_man4",
                        "npc.viking_man5",
                        "npc.viking_woman",
                        "npc.viking_woman2",
                        "npc.viking_woman3",
                        "npc.viking_woman4",
                        "npc.viking_woman_indoors",
                    ),
                displayName = "Fremennik citizen",
                level = 45,
                xp = 65.0,
                pouch = "obj.pickpocket_coin_pouch_fremennik",
                coins = 40,
                lowChance = 56,
                highChance = 202,
                failDamage = 2,
            ),
            PickpocketTarget(
                npcs =
                    listOf(
                        "npc.wilderness_bandit",
                        "npc.guard_bandit",
                        "npc.brawling_bandit",
                        "npc.varlamore_bandit_f_1",
                        "npc.varlamore_bandit_f_2",
                        "npc.varlamore_bandit_f_3",
                        "npc.varlamore_bandit_f_4",
                        "npc.varlamore_bandit_m_1",
                        "npc.varlamore_bandit_m_2",
                        "npc.varlamore_bandit_m_3",
                        "npc.varlamore_bandit_m_4",
                    ),
                displayName = "bandit",
                level = 53,
                xp = 79.4,
                pouch = "obj.pickpocket_coin_pouch_bandit",
                coins = 30,
                lowChance = 50,
                highChance = 194,
                failDamage = 3,
            ),
            PickpocketTarget(
                npcs = listOf("npc.knight_of_ardougne", "npc.knight_of_ardougne2", "npc.knight_of_ardougne_f"),
                displayName = "knight",
                level = 55,
                xp = 84.3,
                pouch = "obj.pickpocket_coin_pouch_knight",
                coins = 50,
                lowChance = 46,
                highChance = 190,
                failDamage = 3,
            ),
            PickpocketTarget(
                npcs = listOf("npc.pirate_pickpocketable_1", "npc.pirate_pickpocketable_2", "npc.pirate_pickpocketable_3", "npc.pirate_pickpocketable_4", "npc.pirate_pickpocketable_5"),
                displayName = "pirate",
                level = 55,
                xp = 85.0,
                pouch = "obj.pickpocket_coin_pouch_pirate",
                coins = 40,
                lowChance = 45,
                highChance = 188,
                failDamage = 3,
            ),
            PickpocketTarget(
                npcs = listOf("npc.wom_watchman", "npc.yanille_watchman"),
                displayName = "watchman",
                level = 65,
                xp = 137.5,
                pouch = "obj.pickpocket_coin_pouch_watchman",
                coins = 60,
                lowChance = 38,
                highChance = 180,
                failDamage = 3,
            ),
            PickpocketTarget(
                npcs = listOf("npc.ali_the_guard", "npc.ali_the_guard_multinpc"),
                displayName = "Menaphite thug",
                level = 65,
                xp = 137.5,
                pouch = "obj.pickpocket_coin_pouch_menaphite",
                coins = 60,
                lowChance = 38,
                highChance = 180,
                failDamage = 3,
            ),
            PickpocketTarget(
                npcs = listOf("npc.paladin", "npc.paladin2", "npc.paladin_f", "npc.ardougne_paladin2"),
                displayName = "paladin",
                level = 70,
                xp = 151.75,
                pouch = "obj.pickpocket_coin_pouch_paladin",
                coins = 80,
                lowChance = 30,
                highChance = 170,
                failDamage = 3,
            ),
            PickpocketTarget(
                npcs = listOf("npc.gnome", "npc.gnomefemale"),
                displayName = "gnome",
                level = 75,
                xp = 198.3,
                pouch = "obj.pickpocket_coin_pouch_gnome",
                coins = 300,
                lowChance = 24,
                highChance = 160,
                failDamage = 4,
            ),
            PickpocketTarget(
                npcs = listOf("npc.hero"),
                displayName = "hero",
                level = 80,
                xp = 273.3,
                pouch = "obj.pickpocket_coin_pouch_hero",
                coins = 150,
                lowChance = 18,
                highChance = 150,
                failDamage = 4,
            ),
            PickpocketTarget(
                npcs =
                    listOf(
                        "npc.darkm_vyrewatch_female_1",
                        "npc.darkm_vyrewatch_female_2",
                        "npc.darkm_vyrewatch_female_3",
                        "npc.darkm_vyrewatch_female_4",
                        "npc.darkm_vyrewatch_male_1",
                        "npc.darkm_vyrewatch_male_2",
                        "npc.darkm_vyrewatch_male_3",
                        "npc.darkm_vyrewatch_male_4",
                    ),
                displayName = "vyre",
                level = 82,
                xp = 306.9,
                pouch = "obj.pickpocket_coin_pouch_vyre",
                coins = 300,
                lowChance = 16,
                highChance = 142,
                failDamage = 4,
            ),
            PickpocketTarget(
                npcs =
                    listOf(
                        "npc.gwenith_elf_1",
                        "npc.gwenith_elf_2",
                        "npc.gwenith_elf_3",
                        "npc.gwenith_elf_4",
                        "npc.gwenith_elf_5",
                        "npc.gwenith_elf_6",
                        "npc.mourning_town_elf_1",
                        "npc.mourning_town_elf_2",
                        "npc.mourning_town_elf_3",
                        "npc.mourning_town_elf_4",
                        "npc.mourning_town_elf_5",
                    ),
                displayName = "elf",
                level = 85,
                xp = 353.3,
                pouch = "obj.pickpocket_coin_pouch_elf",
                coins = 280,
                lowChance = 14,
                highChance = 135,
                failDamage = 5,
            ),
            PickpocketTarget(
                npcs =
                    listOf(
                        "npc.varlamore_citizen_rich_f_1",
                        "npc.varlamore_citizen_rich_f_2",
                        "npc.varlamore_citizen_rich_f_3",
                        "npc.varlamore_citizen_rich_f_4",
                        "npc.varlamore_citizen_rich_f_5",
                        "npc.varlamore_citizen_rich_m_1",
                        "npc.varlamore_citizen_rich_m_2",
                        "npc.varlamore_citizen_rich_m_3",
                        "npc.varlamore_citizen_rich_m_4",
                        "npc.varlamore_citizen_rich_m_5",
                    ),
                displayName = "wealthy citizen",
                level = 50,
                xp = 96.2,
                pouch = "obj.pickpocket_coin_pouch_varlamore_wealthy",
                coins = 85,
                lowChance = 52,
                highChance = 200,
                failDamage = 2,
            ),
        )

    val pouches: Map<String, Int> =
        pickpocketTargets.mapNotNull { target -> target.pouch?.let { it to target.coins } }.toMap()

    val stallTargets =
        listOf(
            StallTarget(
                locIds = intArrayOf(11730, 4874),
                displayName = "bakery stall",
                level = 5,
                xp = 16.0,
                rewards = listOf(ThievingReward("obj.cake"), ThievingReward("obj.bread")),
                emptyLocId = EMPTY_MARKET_STALL,
                respawnTicks = 20,
            ),
            StallTarget(
                locIds = intArrayOf(11729),
                displayName = "silk stall",
                level = 20,
                xp = 24.0,
                rewards = listOf(ThievingReward("obj.silk")),
                emptyLocId = EMPTY_MARKET_STALL,
                respawnTicks = 35,
            ),
            StallTarget(
                locIds = intArrayOf(11732),
                displayName = "fur stall",
                level = 35,
                xp = 36.0,
                rewards = listOf(ThievingReward("obj.fur")),
                emptyLocId = EMPTY_MARKET_STALL,
                respawnTicks = 50,
            ),
            StallTarget(
                locIds = intArrayOf(11733),
                displayName = "spice stall",
                level = 65,
                xp = 81.3,
                rewards = listOf(ThievingReward("obj.spicespot")),
                emptyLocId = EMPTY_MARKET_STALL,
                respawnTicks = 80,
            ),
            StallTarget(
                locIds = intArrayOf(7053),
                displayName = "seed stall",
                level = 27,
                xp = 10.0,
                rewards =
                    listOf(
                        ThievingReward("obj.potato_seed", 3),
                        ThievingReward("obj.onion_seed", 2),
                        ThievingReward("obj.cabbage_seed", 2),
                        ThievingReward("obj.tomato_seed", 1),
                        ThievingReward("obj.sweetcorn_seed", 1),
                        ThievingReward("obj.strawberry_seed", 1),
                    ),
                emptyLocId = EMPTY_MARKET_STALL,
                respawnTicks = 40,
            ),
            StallTarget(
                locIds = intArrayOf(28823, 28824),
                displayName = "fruit stall",
                level = 25,
                xp = 28.5,
                rewards = listOf(ThievingReward("obj.banana"), ThievingReward("obj.redberries"), ThievingReward("obj.jangerberries")),
                emptyLocId = EMPTY_MARKET_STALL,
                respawnTicks = 30,
            ),
            StallTarget(
                locIds = intArrayOf(14011, 14012),
                displayName = "wine stall",
                level = 22,
                xp = 27.0,
                rewards = listOf(ThievingReward("obj.jug_wine")),
                emptyLocId = EMPTY_MARKET_STALL,
                respawnTicks = 30,
            ),
            StallTarget(
                locIds = intArrayOf(20332),
                displayName = "crafting stall",
                level = 5,
                xp = 16.0,
                rewards = listOf(ThievingReward("obj.chisel"), ThievingReward("obj.hammer"), ThievingReward("obj.gold_ring")),
                emptyLocId = EMPTY_MARKET_STALL,
                respawnTicks = 30,
            ),
        )

    val chestTargets =
        listOf(
            ChestTarget(
                locIds = intArrayOf(28785),
                displayName = "locked chest",
                level = 13,
                xp = 7.8,
                rewards = listOf(ThievingReward(COINS, 10)),
                openLocId = 28793,
                respawnTicks = 80,
            ),
            ChestTarget(
                locIds = intArrayOf(32054),
                displayName = "locked chest",
                level = 28,
                xp = 25.0,
                rewards = listOf(ThievingReward(COINS, 50), ThievingReward("obj.lockpick")),
                openLocId = 32057,
                respawnTicks = 100,
            ),
            ChestTarget(
                locIds = intArrayOf(48756),
                displayName = "locked stone chest",
                level = 64,
                xp = 280.0,
                rewards = listOf(ThievingReward(COINS, 250), ThievingReward("obj.ranarr_seed"), ThievingReward("obj.limpwurt_seed")),
                openLocId = 48757,
                respawnTicks = 120,
            ),
        )
}
