package org.rsmod.content.skills.construction

enum class ConstructionHotspotKind(
    val displayName: String,
    val locIds: List<Int>,
) {
    Chair(
        displayName = "chair space",
        locIds = listOf(4515, 4516, 4517),
    ),
    Bookcase(
        displayName = "bookcase space",
        locIds = listOf(4521, 4522),
    ),
    DiningTable(
        displayName = "table space",
        locIds = listOf(15298),
    ),
    KitchenTable(
        displayName = "kitchen table space",
        locIds = listOf(15405),
    ),
    Larder(
        displayName = "larder space",
        locIds = listOf(15403),
    ),
    Bed(
        displayName = "bed space",
        locIds = listOf(15260),
    ),
    Wardrobe(
        displayName = "wardrobe space",
        locIds = listOf(15261),
    ),
    Dresser(
        displayName = "dresser space",
        locIds = listOf(15262),
    ),
    Altar(
        displayName = "altar space",
        locIds = listOf(15270),
    ),
    PortalFrame(
        displayName = "portal space",
        locIds = listOf(15406, 15407, 15408),
    ),
}

data class ConstructionRecipe(
    val displayName: String,
    val level: Int,
    val xp: Double,
    val plank: String,
    val plankCount: Int,
    val nailCount: Int = 0,
    val flatpack: String? = null,
    val hotspotKind: ConstructionHotspotKind? = null,
    val builtLocId: Int? = null,
    val extraMaterials: List<ConstructionMaterial> = emptyList(),
)

data class ConstructionMaterial(
    val obj: String,
    val count: Int,
)

object ConstructionDefinitions {
    const val SAW = "obj.poh_saw"
    const val CRYSTAL_SAW = "obj.eyeglo_crystal_saw"
    const val WEARABLE_SAW = "obj.wearable_saw"
    const val WEARABLE_SAW_OFFHAND = "obj.wearable_saw_offhand"

    const val HAMMER = "obj.hammer"
    const val IMCANDO_HAMMER = "obj.imcando_hammer"
    const val IMCANDO_HAMMER_OFFHAND = "obj.imcando_hammer_offhand"

    const val BUILD_ANIM = "seq.human_poh_build"
    const val BUILD_DELAY = 3

    val saws: Set<String> =
        setOf(
            SAW,
            CRYSTAL_SAW,
            WEARABLE_SAW,
            WEARABLE_SAW_OFFHAND,
        )

    val hammers: Set<String> =
        setOf(
            HAMMER,
            IMCANDO_HAMMER,
            IMCANDO_HAMMER_OFFHAND,
        )

    val nails: List<String> =
        listOf(
            "obj.nails",
            "obj.nails_bronze",
            "obj.nails_iron",
            "obj.nails_black",
            "obj.nails_mithril",
            "obj.nails_adamant",
            "obj.nails_rune",
            "obj.nails_dragon",
        )

    val portalLocIds: List<Int> =
        listOf(
            15477,
            15478,
            15479,
            15480,
            15481,
            28822,
            30172,
        )

    private fun flatpackOnly(
        displayName: String,
        level: Int,
        xp: Double,
        plank: String,
        plankCount: Int,
        flatpack: String,
        nailCount: Int = 0,
        extraMaterials: List<ConstructionMaterial> = emptyList(),
    ): ConstructionRecipe =
        ConstructionRecipe(
            displayName = displayName,
            level = level,
            xp = xp,
            plank = plank,
            plankCount = plankCount,
            nailCount = nailCount,
            flatpack = flatpack,
            extraMaterials = extraMaterials,
        )

    val recipes: List<ConstructionRecipe> =
        listOf(
            ConstructionRecipe(
                displayName = "crude wooden chair",
                level = 1,
                xp = 58.0,
                plank = "obj.woodplank",
                plankCount = 2,
                nailCount = 2,
                flatpack = "obj.poh_flatpack_diningchair1",
                hotspotKind = ConstructionHotspotKind.Chair,
                builtLocId = 6752,
            ),
            ConstructionRecipe(
                displayName = "wooden chair",
                level = 8,
                xp = 87.0,
                plank = "obj.woodplank",
                plankCount = 3,
                nailCount = 3,
                flatpack = "obj.poh_flatpack_diningchair2",
                hotspotKind = ConstructionHotspotKind.Chair,
                builtLocId = 6753,
            ),
            ConstructionRecipe(
                displayName = "rocking chair",
                level = 14,
                xp = 87.0,
                plank = "obj.woodplank",
                plankCount = 3,
                nailCount = 3,
                flatpack = "obj.poh_flatpack_diningchair3",
                hotspotKind = ConstructionHotspotKind.Chair,
                builtLocId = 6754,
            ),
            ConstructionRecipe(
                displayName = "oak chair",
                level = 19,
                xp = 120.0,
                plank = "obj.plank_oak",
                plankCount = 2,
                nailCount = 0,
                flatpack = "obj.poh_flatpack_diningchair4",
                hotspotKind = ConstructionHotspotKind.Chair,
                builtLocId = 6755,
            ),
            ConstructionRecipe(
                displayName = "oak armchair",
                level = 26,
                xp = 180.0,
                plank = "obj.plank_oak",
                plankCount = 3,
                nailCount = 0,
                flatpack = "obj.poh_flatpack_armchair2",
                hotspotKind = ConstructionHotspotKind.Chair,
                builtLocId = 6756,
            ),
            ConstructionRecipe(
                displayName = "teak armchair",
                level = 35,
                xp = 180.0,
                plank = "obj.plank_teak",
                plankCount = 2,
                nailCount = 0,
                flatpack = "obj.poh_flatpack_armchair3",
                hotspotKind = ConstructionHotspotKind.Chair,
                builtLocId = 6757,
            ),
            ConstructionRecipe(
                displayName = "mahogany armchair",
                level = 50,
                xp = 280.0,
                plank = "obj.plank_mahogany",
                plankCount = 2,
                nailCount = 0,
                flatpack = "obj.poh_flatpack_armchair4",
                hotspotKind = ConstructionHotspotKind.Chair,
                builtLocId = 6758,
            ),
            ConstructionRecipe(
                displayName = "wooden bookcase",
                level = 4,
                xp = 115.0,
                plank = "obj.woodplank",
                plankCount = 4,
                nailCount = 4,
                flatpack = "obj.poh_flatpack_bookcase1",
                hotspotKind = ConstructionHotspotKind.Bookcase,
                builtLocId = 6768,
            ),
            ConstructionRecipe(
                displayName = "oak bookcase",
                level = 29,
                xp = 180.0,
                plank = "obj.plank_oak",
                plankCount = 3,
                nailCount = 0,
                flatpack = "obj.poh_flatpack_bookcase2",
                hotspotKind = ConstructionHotspotKind.Bookcase,
                builtLocId = 6769,
            ),
            ConstructionRecipe(
                displayName = "mahogany bookcase",
                level = 40,
                xp = 420.0,
                plank = "obj.plank_mahogany",
                plankCount = 3,
                nailCount = 0,
                flatpack = "obj.poh_flatpack_bookcase3",
                hotspotKind = ConstructionHotspotKind.Bookcase,
                builtLocId = 6770,
            ),
            ConstructionRecipe(
                displayName = "wooden dining table",
                level = 10,
                xp = 115.0,
                plank = "obj.woodplank",
                plankCount = 4,
                nailCount = 4,
                flatpack = "obj.poh_flatpack_diningtable1",
                hotspotKind = ConstructionHotspotKind.DiningTable,
                builtLocId = 13293,
            ),
            ConstructionRecipe(
                displayName = "oak dining table",
                level = 22,
                xp = 240.0,
                plank = "obj.plank_oak",
                plankCount = 4,
                nailCount = 0,
                flatpack = "obj.poh_flatpack_diningtable2",
                hotspotKind = ConstructionHotspotKind.DiningTable,
                builtLocId = 13294,
            ),
            ConstructionRecipe(
                displayName = "carved oak dining table",
                level = 31,
                xp = 360.0,
                plank = "obj.plank_oak",
                plankCount = 6,
                nailCount = 0,
                flatpack = "obj.poh_flatpack_diningtable3",
                hotspotKind = ConstructionHotspotKind.DiningTable,
                builtLocId = 13295,
            ),
            ConstructionRecipe(
                displayName = "teak dining table",
                level = 38,
                xp = 360.0,
                plank = "obj.plank_teak",
                plankCount = 4,
                nailCount = 0,
                flatpack = "obj.poh_flatpack_diningtable4",
                hotspotKind = ConstructionHotspotKind.DiningTable,
                builtLocId = 13296,
            ),
            ConstructionRecipe(
                displayName = "carved teak dining table",
                level = 45,
                xp = 540.0,
                plank = "obj.plank_teak",
                plankCount = 6,
                nailCount = 0,
                flatpack = "obj.poh_flatpack_diningtable5",
                hotspotKind = ConstructionHotspotKind.DiningTable,
                builtLocId = 13297,
            ),
            ConstructionRecipe(
                displayName = "mahogany dining table",
                level = 52,
                xp = 840.0,
                plank = "obj.plank_mahogany",
                plankCount = 6,
                nailCount = 0,
                flatpack = "obj.poh_flatpack_diningtable6",
                hotspotKind = ConstructionHotspotKind.DiningTable,
                builtLocId = 13298,
            ),
            ConstructionRecipe(
                displayName = "opulent dining table",
                level = 72,
                xp = 1760.0,
                plank = "obj.plank_mahogany",
                plankCount = 6,
                nailCount = 0,
                flatpack = "obj.poh_flatpack_diningtable7",
                hotspotKind = ConstructionHotspotKind.DiningTable,
                builtLocId = 13299,
                extraMaterials = listOf(ConstructionMaterial("obj.marble_block", 4)),
            ),
            ConstructionRecipe(
                displayName = "wooden kitchen table",
                level = 12,
                xp = 87.0,
                plank = "obj.woodplank",
                plankCount = 3,
                nailCount = 3,
                flatpack = "obj.poh_flatpack_kitchentable1",
                hotspotKind = ConstructionHotspotKind.KitchenTable,
                builtLocId = 13577,
            ),
            ConstructionRecipe(
                displayName = "oak kitchen table",
                level = 32,
                xp = 180.0,
                plank = "obj.plank_oak",
                plankCount = 3,
                flatpack = "obj.poh_flatpack_kitchentable2",
                hotspotKind = ConstructionHotspotKind.KitchenTable,
                builtLocId = 13578,
            ),
            ConstructionRecipe(
                displayName = "teak kitchen table",
                level = 52,
                xp = 270.0,
                plank = "obj.plank_teak",
                plankCount = 3,
                flatpack = "obj.poh_flatpack_kitchentable3",
                hotspotKind = ConstructionHotspotKind.KitchenTable,
                builtLocId = 13579,
            ),
            ConstructionRecipe(
                displayName = "wooden larder",
                level = 9,
                xp = 228.0,
                plank = "obj.woodplank",
                plankCount = 8,
                nailCount = 8,
                flatpack = "obj.poh_larder_1",
                hotspotKind = ConstructionHotspotKind.Larder,
                builtLocId = 13565,
            ),
            ConstructionRecipe(
                displayName = "oak larder",
                level = 33,
                xp = 480.0,
                plank = "obj.plank_oak",
                plankCount = 8,
                flatpack = "obj.poh_larder_2",
                hotspotKind = ConstructionHotspotKind.Larder,
                builtLocId = 13566,
            ),
            ConstructionRecipe(
                displayName = "teak larder",
                level = 43,
                xp = 750.0,
                plank = "obj.plank_teak",
                plankCount = 8,
                flatpack = "obj.poh_larder_3",
                hotspotKind = ConstructionHotspotKind.Larder,
                builtLocId = 13567,
            ),
            ConstructionRecipe(
                displayName = "wooden bed",
                level = 20,
                xp = 117.0,
                plank = "obj.woodplank",
                plankCount = 3,
                nailCount = 3,
                flatpack = "obj.poh_flatpack_bed1",
                hotspotKind = ConstructionHotspotKind.Bed,
                builtLocId = 13148,
                extraMaterials = listOf(ConstructionMaterial("obj.cloth", 2)),
            ),
            ConstructionRecipe(
                displayName = "oak bed",
                level = 30,
                xp = 210.0,
                plank = "obj.plank_oak",
                plankCount = 3,
                flatpack = "obj.poh_flatpack_bed2",
                hotspotKind = ConstructionHotspotKind.Bed,
                builtLocId = 13149,
                extraMaterials = listOf(ConstructionMaterial("obj.cloth", 2)),
            ),
            ConstructionRecipe(
                displayName = "large oak bed",
                level = 34,
                xp = 330.0,
                plank = "obj.plank_oak",
                plankCount = 5,
                flatpack = "obj.poh_flatpack_bed3",
                hotspotKind = ConstructionHotspotKind.Bed,
                builtLocId = 13150,
                extraMaterials = listOf(ConstructionMaterial("obj.cloth", 2)),
            ),
            ConstructionRecipe(
                displayName = "teak bed",
                level = 40,
                xp = 300.0,
                plank = "obj.plank_teak",
                plankCount = 3,
                flatpack = "obj.poh_flatpack_bed4",
                hotspotKind = ConstructionHotspotKind.Bed,
                builtLocId = 13151,
                extraMaterials = listOf(ConstructionMaterial("obj.cloth", 2)),
            ),
            ConstructionRecipe(
                displayName = "large teak bed",
                level = 45,
                xp = 480.0,
                plank = "obj.plank_teak",
                plankCount = 5,
                flatpack = "obj.poh_flatpack_bed5",
                hotspotKind = ConstructionHotspotKind.Bed,
                builtLocId = 13152,
                extraMaterials = listOf(ConstructionMaterial("obj.cloth", 2)),
            ),
            ConstructionRecipe(
                displayName = "four-poster bed",
                level = 53,
                xp = 450.0,
                plank = "obj.plank_mahogany",
                plankCount = 3,
                flatpack = "obj.poh_flatpack_bed6",
                hotspotKind = ConstructionHotspotKind.Bed,
                builtLocId = 13153,
                extraMaterials = listOf(ConstructionMaterial("obj.cloth", 2)),
            ),
            ConstructionRecipe(
                displayName = "gilded four-poster bed",
                level = 60,
                xp = 1330.0,
                plank = "obj.plank_mahogany",
                plankCount = 5,
                flatpack = "obj.poh_flatpack_bed7",
                hotspotKind = ConstructionHotspotKind.Bed,
                builtLocId = 13154,
                extraMaterials =
                    listOf(
                        ConstructionMaterial("obj.cloth", 2),
                        ConstructionMaterial("obj.gold_leaf", 2),
                    ),
            ),
            ConstructionRecipe(
                displayName = "shaving stand",
                level = 21,
                xp = 30.0,
                plank = "obj.woodplank",
                plankCount = 1,
                nailCount = 1,
                flatpack = "obj.poh_flatpack_dresser1",
                hotspotKind = ConstructionHotspotKind.Dresser,
                builtLocId = 13162,
                extraMaterials = listOf(ConstructionMaterial("obj.molten_glass", 1)),
            ),
            ConstructionRecipe(
                displayName = "oak shaving stand",
                level = 29,
                xp = 61.0,
                plank = "obj.plank_oak",
                plankCount = 1,
                flatpack = "obj.poh_flatpack_dresser2",
                hotspotKind = ConstructionHotspotKind.Dresser,
                builtLocId = 13163,
                extraMaterials = listOf(ConstructionMaterial("obj.molten_glass", 1)),
            ),
            ConstructionRecipe(
                displayName = "oak dresser",
                level = 37,
                xp = 121.0,
                plank = "obj.plank_oak",
                plankCount = 2,
                flatpack = "obj.poh_flatpack_dresser3",
                hotspotKind = ConstructionHotspotKind.Dresser,
                builtLocId = 13164,
                extraMaterials = listOf(ConstructionMaterial("obj.molten_glass", 1)),
            ),
            ConstructionRecipe(
                displayName = "teak dresser",
                level = 46,
                xp = 181.0,
                plank = "obj.plank_teak",
                plankCount = 2,
                flatpack = "obj.poh_flatpack_dresser4",
                hotspotKind = ConstructionHotspotKind.Dresser,
                builtLocId = 13165,
                extraMaterials = listOf(ConstructionMaterial("obj.molten_glass", 1)),
            ),
            ConstructionRecipe(
                displayName = "fancy teak dresser",
                level = 56,
                xp = 182.0,
                plank = "obj.plank_teak",
                plankCount = 2,
                flatpack = "obj.poh_flatpack_dresser5",
                hotspotKind = ConstructionHotspotKind.Dresser,
                builtLocId = 13166,
                extraMaterials = listOf(ConstructionMaterial("obj.molten_glass", 2)),
            ),
            ConstructionRecipe(
                displayName = "mahogany dresser",
                level = 64,
                xp = 281.0,
                plank = "obj.plank_mahogany",
                plankCount = 2,
                flatpack = "obj.poh_flatpack_dresser6",
                hotspotKind = ConstructionHotspotKind.Dresser,
                builtLocId = 13167,
                extraMaterials = listOf(ConstructionMaterial("obj.molten_glass", 1)),
            ),
            ConstructionRecipe(
                displayName = "gilded dresser",
                level = 74,
                xp = 582.0,
                plank = "obj.plank_mahogany",
                plankCount = 2,
                flatpack = "obj.poh_flatpack_dresser7",
                hotspotKind = ConstructionHotspotKind.Dresser,
                builtLocId = 13168,
                extraMaterials =
                    listOf(
                        ConstructionMaterial("obj.molten_glass", 2),
                        ConstructionMaterial("obj.gold_leaf", 1),
                    ),
            ),
            ConstructionRecipe(
                displayName = "wooden wardrobe",
                level = 14,
                xp = 87.0,
                plank = "obj.woodplank",
                plankCount = 3,
                nailCount = 3,
                flatpack = "obj.poh_flatpack_wardrobe1",
                hotspotKind = ConstructionHotspotKind.Wardrobe,
                builtLocId = 13155,
            ),
            ConstructionRecipe(
                displayName = "oak wardrobe",
                level = 29,
                xp = 180.0,
                plank = "obj.plank_oak",
                plankCount = 3,
                flatpack = "obj.poh_flatpack_wardrobe2",
                hotspotKind = ConstructionHotspotKind.Wardrobe,
                builtLocId = 13156,
            ),
            ConstructionRecipe(
                displayName = "carved oak wardrobe",
                level = 39,
                xp = 240.0,
                plank = "obj.plank_oak",
                plankCount = 4,
                flatpack = "obj.poh_flatpack_wardrobe3",
                hotspotKind = ConstructionHotspotKind.Wardrobe,
                builtLocId = 13157,
            ),
            ConstructionRecipe(
                displayName = "teak wardrobe",
                level = 49,
                xp = 270.0,
                plank = "obj.plank_teak",
                plankCount = 3,
                flatpack = "obj.poh_flatpack_wardrobe4",
                hotspotKind = ConstructionHotspotKind.Wardrobe,
                builtLocId = 13158,
            ),
            ConstructionRecipe(
                displayName = "carved teak wardrobe",
                level = 59,
                xp = 360.0,
                plank = "obj.plank_teak",
                plankCount = 4,
                flatpack = "obj.poh_flatpack_wardrobe5",
                hotspotKind = ConstructionHotspotKind.Wardrobe,
                builtLocId = 13159,
            ),
            ConstructionRecipe(
                displayName = "mahogany wardrobe",
                level = 69,
                xp = 420.0,
                plank = "obj.plank_mahogany",
                plankCount = 3,
                flatpack = "obj.poh_flatpack_wardrobe6",
                hotspotKind = ConstructionHotspotKind.Wardrobe,
                builtLocId = 13160,
            ),
            ConstructionRecipe(
                displayName = "gilded wardrobe",
                level = 79,
                xp = 720.0,
                plank = "obj.plank_mahogany",
                plankCount = 3,
                flatpack = "obj.poh_flatpack_wardrobe7",
                hotspotKind = ConstructionHotspotKind.Wardrobe,
            builtLocId = 13161,
            extraMaterials = listOf(ConstructionMaterial("obj.gold_leaf", 1)),
        ),
        ConstructionRecipe(
            displayName = "oak altar",
            level = 45,
            xp = 240.0,
            plank = "obj.plank_oak",
            plankCount = 4,
            hotspotKind = ConstructionHotspotKind.Altar,
            builtLocId = 13179,
        ),
        ConstructionRecipe(
            displayName = "teak altar",
            level = 50,
            xp = 360.0,
            plank = "obj.plank_teak",
            plankCount = 4,
            hotspotKind = ConstructionHotspotKind.Altar,
            builtLocId = 13182,
        ),
        ConstructionRecipe(
            displayName = "cloth-covered teak altar",
            level = 56,
            xp = 390.0,
            plank = "obj.plank_teak",
            plankCount = 4,
            hotspotKind = ConstructionHotspotKind.Altar,
            builtLocId = 13185,
            extraMaterials = listOf(ConstructionMaterial("obj.cloth", 2)),
        ),
        ConstructionRecipe(
            displayName = "mahogany altar",
            level = 60,
            xp = 590.0,
            plank = "obj.plank_mahogany",
            plankCount = 4,
            hotspotKind = ConstructionHotspotKind.Altar,
            builtLocId = 13188,
        ),
        ConstructionRecipe(
            displayName = "limestone altar",
            level = 64,
            xp = 910.0,
            plank = "obj.limestonebrick",
            plankCount = 6,
            hotspotKind = ConstructionHotspotKind.Altar,
            builtLocId = 13191,
        ),
        ConstructionRecipe(
            displayName = "marble altar",
            level = 70,
            xp = 1030.0,
            plank = "obj.marble_block",
            plankCount = 2,
            hotspotKind = ConstructionHotspotKind.Altar,
            builtLocId = 13194,
        ),
        ConstructionRecipe(
            displayName = "gilded altar",
            level = 75,
            xp = 2230.0,
            plank = "obj.marble_block",
            plankCount = 2,
            hotspotKind = ConstructionHotspotKind.Altar,
            builtLocId = 13197,
            extraMaterials =
                listOf(
                    ConstructionMaterial("obj.cloth", 2),
                    ConstructionMaterial("obj.gold_leaf", 4),
                ),
        ),
        ConstructionRecipe(
            displayName = "teak portal frame",
            level = 50,
            xp = 270.0,
            plank = "obj.plank_teak",
            plankCount = 3,
            hotspotKind = ConstructionHotspotKind.PortalFrame,
            builtLocId = 13636,
        ),
        ConstructionRecipe(
            displayName = "mahogany portal frame",
            level = 65,
            xp = 420.0,
            plank = "obj.plank_mahogany",
            plankCount = 3,
            hotspotKind = ConstructionHotspotKind.PortalFrame,
            builtLocId = 13637,
        ),
        ConstructionRecipe(
            displayName = "marble portal frame",
            level = 80,
            xp = 1500.0,
            plank = "obj.marble_block",
            plankCount = 3,
            hotspotKind = ConstructionHotspotKind.PortalFrame,
            builtLocId = 13638,
        ),
        flatpackOnly(
            displayName = "oak clock",
            level = 25,
                xp = 142.0,
                plank = "obj.plank_oak",
                plankCount = 2,
                flatpack = "obj.poh_flatpack_clock1",
                extraMaterials = listOf(ConstructionMaterial("obj.poh_clockwork_mechanism", 1)),
            ),
            flatpackOnly(
                displayName = "teak clock",
                level = 55,
                xp = 202.0,
                plank = "obj.plank_teak",
                plankCount = 2,
                flatpack = "obj.poh_flatpack_clock2",
                extraMaterials = listOf(ConstructionMaterial("obj.poh_clockwork_mechanism", 1)),
            ),
            flatpackOnly(
                displayName = "gilded clock",
                level = 85,
                xp = 602.0,
                plank = "obj.plank_mahogany",
                plankCount = 2,
                flatpack = "obj.poh_flatpack_clock3",
                extraMaterials =
                    listOf(
                        ConstructionMaterial("obj.poh_clockwork_mechanism", 1),
                        ConstructionMaterial("obj.gold_leaf", 1),
                    ),
            ),
            flatpackOnly(
                displayName = "oak toy box",
                level = 50,
                xp = 120.0,
                plank = "obj.plank_oak",
                plankCount = 2,
                flatpack = "obj.poh_flatpack_toy_box",
            ),
            flatpackOnly(
                displayName = "teak toy box",
                level = 68,
                xp = 180.0,
                plank = "obj.plank_teak",
                plankCount = 2,
                flatpack = "obj.poh_flatpack_toy_box2",
            ),
            flatpackOnly(
                displayName = "mahogany toy box",
                level = 86,
                xp = 280.0,
                plank = "obj.plank_mahogany",
                plankCount = 2,
                flatpack = "obj.poh_flatpack_toy_box3",
            ),
            flatpackOnly(
                displayName = "oak armour case",
                level = 46,
                xp = 180.0,
                plank = "obj.plank_oak",
                plankCount = 3,
                flatpack = "obj.poh_flatpack_armour_case",
            ),
            flatpackOnly(
                displayName = "teak armour case",
                level = 64,
                xp = 270.0,
                plank = "obj.plank_teak",
                plankCount = 3,
                flatpack = "obj.poh_flatpack_armour_case2",
            ),
            flatpackOnly(
                displayName = "mahogany armour case",
                level = 82,
                xp = 420.0,
                plank = "obj.plank_mahogany",
                plankCount = 3,
                flatpack = "obj.poh_flatpack_armour_case3",
            ),
            flatpackOnly(
                displayName = "oak treasure chest",
                level = 48,
                xp = 120.0,
                plank = "obj.plank_oak",
                plankCount = 2,
                flatpack = "obj.poh_flatpack_treasure_chest",
            ),
            flatpackOnly(
                displayName = "teak treasure chest",
                level = 66,
                xp = 180.0,
                plank = "obj.plank_teak",
                plankCount = 2,
                flatpack = "obj.poh_flatpack_treasure_chest2",
            ),
            flatpackOnly(
                displayName = "mahogany treasure chest",
                level = 84,
                xp = 280.0,
                plank = "obj.plank_mahogany",
                plankCount = 2,
                flatpack = "obj.poh_flatpack_treasure_chest3",
            ),
        )

    val flatpackRecipes: List<ConstructionRecipe> = recipes.filter { it.flatpack != null }

    val recipesByPlank: Map<String, List<ConstructionRecipe>> =
        flatpackRecipes.groupBy(ConstructionRecipe::plank)

    val recipesByFlatpack: Map<String, ConstructionRecipe> =
        flatpackRecipes.associateBy { it.flatpack ?: error("Missing flatpack output.") }

    val recipesByHotspot: Map<ConstructionHotspotKind, List<ConstructionRecipe>> =
        recipes
            .mapNotNull { recipe -> recipe.hotspotKind?.let { kind -> kind to recipe } }
            .groupBy({ it.first }, { it.second })

    val hotspotKindByLocId: Map<Int, ConstructionHotspotKind> =
        ConstructionHotspotKind.entries.flatMap { kind -> kind.locIds.map { it to kind } }.toMap()

    val hotspotLocIds: Set<Int> = hotspotKindByLocId.keys

    val builtLocToHotspotLocId: Map<Int, Int> =
        recipes
            .mapNotNull { recipe ->
                val hotspotKind = recipe.hotspotKind ?: return@mapNotNull null
                val builtLocId = recipe.builtLocId ?: return@mapNotNull null
                builtLocId to hotspotKind.locIds.first()
            }
            .toMap()
}
