[gamevals.queue]
crafting_battlestaff = 64
crafting_gem_cut = 65
crafting_glassblowing = 66
crafting_leather = 67
crafting_spinning = 68
crafting_jewellery = 69
crafting_jewellery_stringing = 70
crafting_pottery_shape = 71
crafting_pottery_fire = 72
crafting_amethyst = 73
crafting_tanning = 74
