package org.rsmod.content.skills.farming

internal enum class FarmingPatchKind(
    val displayName: String,
    val cleanLocIds: IntArray,
) {
    Allotment(
        displayName = "allotment",
        cleanLocIds = intArrayOf(8573, 8574, 8575, 8576, 8577, 8578, 8579),
    ),
    Herb(
        displayName = "herb patch",
        cleanLocIds = intArrayOf(8132, 8133, 8134, 8135, 8136, 8137, 8138, 18818, 18819, 18820, 18821, 15066),
    ),
    Flower(
        displayName = "flower patch",
        cleanLocIds = intArrayOf(7840, 7841, 7842, 7843, 7844, 7845, 7846),
    ),
    Bush(
        displayName = "bush patch",
        cleanLocIds = intArrayOf(7573, 7574, 7575, 7576),
    ),
    Hops(
        displayName = "hops patch",
        cleanLocIds = intArrayOf(8207, 8208, 8209, 8210),
    ),
    Mushroom(
        displayName = "mushroom patch",
        cleanLocIds = intArrayOf(8311, 8312, 8313, 8314),
    ),
    Cactus(
        displayName = "cactus patch",
        cleanLocIds = intArrayOf(7743, 7744, 7745, 7746),
    ),
    Tree(
        displayName = "tree patch",
        cleanLocIds = intArrayOf(8392, 8393, 8394, 8395),
    ),
    FruitTree(
        displayName = "fruit tree patch",
        cleanLocIds = intArrayOf(8047, 8048, 8049, 8050),
    ),
    HardwoodTree(
        displayName = "hardwood tree patch",
        cleanLocIds = intArrayOf(30476, 30477, 30478, 30479),
    ),
    Seaweed(
        displayName = "seaweed patch",
        cleanLocIds = intArrayOf(30483, 30484, 30485, 30486),
    ),
    Anima(
        displayName = "anima patch",
        cleanLocIds = intArrayOf(33980, 33981, 33982, 33983),
    ),
    Calquat(
        displayName = "calquat tree patch",
        cleanLocIds = intArrayOf(7772, 7773, 7774, 7775),
    ),
    Celastrus(
        displayName = "celastrus tree patch",
        cleanLocIds = intArrayOf(33695, 33696, 33697, 33698),
    ),
    Redwood(
        displayName = "redwood tree patch",
        cleanLocIds = intArrayOf(34035, 34036, 34037, 34038, 34039, 34040, 34041, 34042, 34043, 34044, 34045, 34046, 34047, 34048, 34049, 34050),
    ),
}

internal enum class FarmingHarvestMode {
    Harvest,
    CheckHealth,
}

internal data class FarmingRecipe(
    val kind: FarmingPatchKind,
    val seed: String,
    val seedCount: Int,
    val product: String?,
    val displayName: String,
    val level: Int,
    val plantXp: Double,
    val harvestXp: Double,
    val minYield: Int,
    val maxYield: Int,
    val growSeconds: Int,
    val plantedLocId: Int,
    val readyLocId: Int,
    val harvestMode: FarmingHarvestMode = FarmingHarvestMode.Harvest,
    val plantTool: String? = "obj.seed_dibber",
    val plantToolMessage: String = "You need a seed dibber to plant seeds.",
    val plantItemName: String = "seed",
)

internal data class FarmingSaplingRecipe(
    val seed: String,
    val pottedSeed: String,
    val sapling: String,
)

internal object FarmingDefinitions {
    const val RAKE = "obj.rake"
    const val SPADE = "obj.spade"
    const val SEED_DIBBER = "obj.seed_dibber"
    const val GARDENING_TROWEL = "obj.gardening_trowel"
    const val PLANT_POT_EMPTY = "obj.plantpot_empty"
    const val BUCKET_EMPTY = "obj.bucket_empty"

    val compostItems =
        mapOf(
            "obj.bucket_compost" to 1,
            "obj.bucket_supercompost" to 2,
            "obj.bucket_ultracompost" to 3,
        )

    val wateringCans =
        (1..8).associate { charges -> "obj.watering_can_$charges" to charges }

    val recipes =
        listOf(
            FarmingRecipe(
                kind = FarmingPatchKind.Allotment,
                seed = "obj.potato_seed",
                seedCount = 3,
                product = "obj.potato",
                displayName = "potatoes",
                level = 1,
                plantXp = 8.0,
                harvestXp = 9.0,
                minYield = 3,
                maxYield = 6,
                growSeconds = 60,
                plantedLocId = 8558,
                readyLocId = 8562,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Allotment,
                seed = "obj.onion_seed",
                seedCount = 3,
                product = "obj.onion",
                displayName = "onions",
                level = 5,
                plantXp = 9.5,
                harvestXp = 10.5,
                minYield = 3,
                maxYield = 6,
                growSeconds = 70,
                plantedLocId = 8580,
                readyLocId = 8584,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Allotment,
                seed = "obj.cabbage_seed",
                seedCount = 3,
                product = "obj.cabbage",
                displayName = "cabbages",
                level = 7,
                plantXp = 10.0,
                harvestXp = 11.5,
                minYield = 3,
                maxYield = 6,
                growSeconds = 80,
                plantedLocId = 8535,
                readyLocId = 8539,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Allotment,
                seed = "obj.tomato_seed",
                seedCount = 3,
                product = "obj.tomato",
                displayName = "tomatoes",
                level = 12,
                plantXp = 12.5,
                harvestXp = 14.0,
                minYield = 3,
                maxYield = 6,
                growSeconds = 90,
                plantedLocId = 8641,
                readyLocId = 8645,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Allotment,
                seed = "obj.sweetcorn_seed",
                seedCount = 3,
                product = "obj.sweetcorn",
                displayName = "sweetcorn",
                level = 20,
                plantXp = 17.0,
                harvestXp = 19.0,
                minYield = 3,
                maxYield = 6,
                growSeconds = 110,
                plantedLocId = 8618,
                readyLocId = 8624,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Allotment,
                seed = "obj.strawberry_seed",
                seedCount = 3,
                product = "obj.strawberry",
                displayName = "strawberries",
                level = 31,
                plantXp = 26.0,
                harvestXp = 29.0,
                minYield = 3,
                maxYield = 6,
                growSeconds = 130,
                plantedLocId = 8595,
                readyLocId = 8601,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Allotment,
                seed = "obj.watermelon_seed",
                seedCount = 3,
                product = "obj.watermelon",
                displayName = "watermelons",
                level = 47,
                plantXp = 48.5,
                harvestXp = 54.5,
                minYield = 3,
                maxYield = 6,
                growSeconds = 150,
                plantedLocId = 8656,
                readyLocId = 8664,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Herb,
                seed = "obj.guam_seed",
                seedCount = 1,
                product = "obj.unidentified_guam",
                displayName = "guam",
                level = 9,
                plantXp = 11.0,
                harvestXp = 12.5,
                minYield = 3,
                maxYield = 7,
                growSeconds = 90,
                plantedLocId = 18822,
                readyLocId = 26828,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Herb,
                seed = "obj.marrentill_seed",
                seedCount = 1,
                product = "obj.unidentified_marrentill",
                displayName = "marrentill",
                level = 14,
                plantXp = 13.5,
                harvestXp = 15.0,
                minYield = 3,
                maxYield = 7,
                growSeconds = 100,
                plantedLocId = 18822,
                readyLocId = 26828,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Herb,
                seed = "obj.tarromin_seed",
                seedCount = 1,
                product = "obj.unidentified_tarromin",
                displayName = "tarromin",
                level = 19,
                plantXp = 16.0,
                harvestXp = 18.0,
                minYield = 3,
                maxYield = 7,
                growSeconds = 110,
                plantedLocId = 18822,
                readyLocId = 26828,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Herb,
                seed = "obj.harralander_seed",
                seedCount = 1,
                product = "obj.unidentified_harralander",
                displayName = "harralander",
                level = 26,
                plantXp = 21.5,
                harvestXp = 24.0,
                minYield = 3,
                maxYield = 7,
                growSeconds = 120,
                plantedLocId = 18822,
                readyLocId = 26828,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Herb,
                seed = "obj.ranarr_seed",
                seedCount = 1,
                product = "obj.unidentified_ranarr",
                displayName = "ranarr",
                level = 32,
                plantXp = 27.0,
                harvestXp = 30.5,
                minYield = 3,
                maxYield = 7,
                growSeconds = 130,
                plantedLocId = 18822,
                readyLocId = 26828,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Herb,
                seed = "obj.snapdragon_seed",
                seedCount = 1,
                product = "obj.unidentified_snapdragon",
                displayName = "snapdragon",
                level = 62,
                plantXp = 87.5,
                harvestXp = 98.5,
                minYield = 3,
                maxYield = 7,
                growSeconds = 160,
                plantedLocId = 18822,
                readyLocId = 26828,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Herb,
                seed = "obj.torstol_seed",
                seedCount = 1,
                product = "obj.unidentified_torstol",
                displayName = "torstol",
                level = 85,
                plantXp = 199.5,
                harvestXp = 224.5,
                minYield = 3,
                maxYield = 7,
                growSeconds = 180,
                plantedLocId = 18822,
                readyLocId = 26828,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Flower,
                seed = "obj.marigold_seed",
                seedCount = 1,
                product = "obj.marigold",
                displayName = "marigolds",
                level = 2,
                plantXp = 8.5,
                harvestXp = 47.0,
                minYield = 1,
                maxYield = 1,
                growSeconds = 60,
                plantedLocId = 7867,
                readyLocId = 7871,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Flower,
                seed = "obj.rosemary_seed",
                seedCount = 1,
                product = "obj.rosemary",
                displayName = "rosemary",
                level = 11,
                plantXp = 12.0,
                harvestXp = 66.5,
                minYield = 1,
                maxYield = 1,
                growSeconds = 70,
                plantedLocId = 7899,
                readyLocId = 7903,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Flower,
                seed = "obj.nasturtium_seed",
                seedCount = 1,
                product = "obj.nasturtium",
                displayName = "nasturtiums",
                level = 24,
                plantXp = 19.5,
                harvestXp = 111.0,
                minYield = 1,
                maxYield = 1,
                growSeconds = 90,
                plantedLocId = 7883,
                readyLocId = 7887,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Flower,
                seed = "obj.limpwurt_seed",
                seedCount = 1,
                product = "obj.limpwurt_root",
                displayName = "limpwurt",
                level = 26,
                plantXp = 21.5,
                harvestXp = 120.0,
                minYield = 3,
                maxYield = 6,
                growSeconds = 100,
                plantedLocId = 7851,
                readyLocId = 7855,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Flower,
                seed = "obj.white_lily_seed",
                seedCount = 1,
                product = "obj.white_lily",
                displayName = "white lilies",
                level = 52,
                plantXp = 70.0,
                harvestXp = 250.0,
                minYield = 1,
                maxYield = 1,
                growSeconds = 120,
                plantedLocId = 33650,
                readyLocId = 33654,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Bush,
                seed = "obj.redberry_bush_seed",
                seedCount = 1,
                product = "obj.redberries",
                displayName = "redberries",
                level = 10,
                plantXp = 11.5,
                harvestXp = 4.5,
                minYield = 4,
                maxYield = 6,
                growSeconds = 120,
                plantedLocId = 7692,
                readyLocId = 7697,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Bush,
                seed = "obj.cadavaberry_bush_seed",
                seedCount = 1,
                product = "obj.cadavaberries",
                displayName = "cadavaberries",
                level = 22,
                plantXp = 18.0,
                harvestXp = 7.0,
                minYield = 4,
                maxYield = 6,
                growSeconds = 140,
                plantedLocId = 7581,
                readyLocId = 7587,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Bush,
                seed = "obj.dwellberry_bush_seed",
                seedCount = 1,
                product = "obj.dwellberries",
                displayName = "dwellberries",
                level = 36,
                plantXp = 31.5,
                harvestXp = 12.0,
                minYield = 4,
                maxYield = 6,
                growSeconds = 160,
                plantedLocId = 7605,
                readyLocId = 7612,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Bush,
                seed = "obj.jangerberry_bush_seed",
                seedCount = 1,
                product = "obj.jangerberries",
                displayName = "jangerberries",
                level = 48,
                plantXp = 50.5,
                harvestXp = 19.0,
                minYield = 4,
                maxYield = 6,
                growSeconds = 180,
                plantedLocId = 7632,
                readyLocId = 7640,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Bush,
                seed = "obj.whiteberry_bush_seed",
                seedCount = 1,
                product = "obj.white_berries",
                displayName = "white berries",
                level = 59,
                plantXp = 78.0,
                harvestXp = 29.0,
                minYield = 4,
                maxYield = 6,
                growSeconds = 200,
                plantedLocId = 7713,
                readyLocId = 7721,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Bush,
                seed = "obj.poisonivy_bush_seed",
                seedCount = 1,
                product = "obj.poisonivy_berries",
                displayName = "poison ivy berries",
                level = 70,
                plantXp = 120.0,
                harvestXp = 45.0,
                minYield = 4,
                maxYield = 6,
                growSeconds = 220,
                plantedLocId = 7662,
                readyLocId = 7670,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Hops,
                seed = "obj.barley_seed",
                seedCount = 4,
                product = "obj.barley",
                displayName = "barley",
                level = 3,
                plantXp = 8.5,
                harvestXp = 9.5,
                minYield = 3,
                maxYield = 8,
                growSeconds = 80,
                plantedLocId = 8192,
                readyLocId = 8196,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Hops,
                seed = "obj.hammerstone_hop_seed",
                seedCount = 4,
                product = "obj.hammerstone_hops",
                displayName = "hammerstone hops",
                level = 4,
                plantXp = 9.0,
                harvestXp = 10.0,
                minYield = 3,
                maxYield = 8,
                growSeconds = 90,
                plantedLocId = 8177,
                readyLocId = 8181,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Hops,
                seed = "obj.asgarnian_hop_seed",
                seedCount = 4,
                product = "obj.asgarnian_hops",
                displayName = "asgarnian hops",
                level = 8,
                plantXp = 10.9,
                harvestXp = 12.0,
                minYield = 3,
                maxYield = 8,
                growSeconds = 100,
                plantedLocId = 8154,
                readyLocId = 8159,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Hops,
                seed = "obj.jute_seed",
                seedCount = 3,
                product = "obj.jute_fibre",
                displayName = "jute fibre",
                level = 13,
                plantXp = 13.0,
                harvestXp = 14.5,
                minYield = 3,
                maxYield = 10,
                growSeconds = 110,
                plantedLocId = 8238,
                readyLocId = 8243,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Hops,
                seed = "obj.yanillian_hop_seed",
                seedCount = 4,
                product = "obj.yanillian_hops",
                displayName = "yanillian hops",
                level = 16,
                plantXp = 14.5,
                harvestXp = 16.0,
                minYield = 3,
                maxYield = 8,
                growSeconds = 120,
                plantedLocId = 8288,
                readyLocId = 8294,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Hops,
                seed = "obj.krandorian_hop_seed",
                seedCount = 4,
                product = "obj.krandorian_hops",
                displayName = "krandorian hops",
                level = 21,
                plantXp = 17.5,
                harvestXp = 19.5,
                minYield = 3,
                maxYield = 8,
                growSeconds = 130,
                plantedLocId = 8211,
                readyLocId = 8218,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Hops,
                seed = "obj.wildblood_hop_seed",
                seedCount = 4,
                product = "obj.wildblood_hops",
                displayName = "wildblood hops",
                level = 28,
                plantXp = 23.0,
                harvestXp = 26.0,
                minYield = 3,
                maxYield = 8,
                growSeconds = 140,
                plantedLocId = 8257,
                readyLocId = 8265,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Mushroom,
                seed = "obj.mushroom_seed",
                seedCount = 1,
                product = "obj.bittercap_mushroom",
                displayName = "bittercap mushrooms",
                level = 53,
                plantXp = 61.5,
                harvestXp = 57.7,
                minYield = 4,
                maxYield = 8,
                growSeconds = 170,
                plantedLocId = 8315,
                readyLocId = 8321,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Cactus,
                seed = "obj.cactus_seed",
                seedCount = 3,
                product = "obj.cactus_spine",
                displayName = "cactus",
                level = 55,
                plantXp = 66.5,
                harvestXp = 25.0,
                minYield = 3,
                maxYield = 6,
                growSeconds = 190,
                plantedLocId = 7747,
                readyLocId = 7754,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Cactus,
                seed = "obj.potato_cactus_seed",
                seedCount = 3,
                product = "obj.potato_cactus",
                displayName = "potato cactus",
                level = 64,
                plantXp = 68.0,
                harvestXp = 68.0,
                minYield = 3,
                maxYield = 6,
                growSeconds = 210,
                plantedLocId = 33734,
                readyLocId = 33741,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Tree,
                seed = "obj.plantpot_oak_sapling",
                seedCount = 1,
                product = null,
                displayName = "oak tree",
                level = 15,
                plantXp = 14.0,
                harvestXp = 467.3,
                minYield = 0,
                maxYield = 0,
                growSeconds = 240,
                plantedLocId = 8462,
                readyLocId = 8466,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Tree,
                seed = "obj.plantpot_willow_sapling",
                seedCount = 1,
                product = null,
                displayName = "willow tree",
                level = 30,
                plantXp = 25.0,
                harvestXp = 1456.5,
                minYield = 0,
                maxYield = 0,
                growSeconds = 270,
                plantedLocId = 8481,
                readyLocId = 8487,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Tree,
                seed = "obj.plantpot_maple_sapling",
                seedCount = 1,
                product = null,
                displayName = "maple tree",
                level = 45,
                plantXp = 45.0,
                harvestXp = 3403.4,
                minYield = 0,
                maxYield = 0,
                growSeconds = 300,
                plantedLocId = 8435,
                readyLocId = 8443,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Tree,
                seed = "obj.plantpot_yew_sapling",
                seedCount = 1,
                product = null,
                displayName = "yew tree",
                level = 60,
                plantXp = 81.0,
                harvestXp = 7069.9,
                minYield = 0,
                maxYield = 0,
                growSeconds = 330,
                plantedLocId = 8502,
                readyLocId = 8512,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Tree,
                seed = "obj.plantpot_magic_tree_sapling",
                seedCount = 1,
                product = null,
                displayName = "magic tree",
                level = 75,
                plantXp = 145.5,
                harvestXp = 13768.3,
                minYield = 0,
                maxYield = 0,
                growSeconds = 360,
                plantedLocId = 8396,
                readyLocId = 8408,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.FruitTree,
                seed = "obj.plantpot_apple_sapling",
                seedCount = 1,
                product = "obj.cooking_apple",
                displayName = "apple tree",
                level = 27,
                plantXp = 22.0,
                harvestXp = 1199.5,
                minYield = 6,
                maxYield = 6,
                growSeconds = 300,
                plantedLocId = 7935,
                readyLocId = 7941,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.FruitTree,
                seed = "obj.plantpot_banana_sapling",
                seedCount = 1,
                product = "obj.banana",
                displayName = "banana tree",
                level = 33,
                plantXp = 28.0,
                harvestXp = 1750.5,
                minYield = 6,
                maxYield = 6,
                growSeconds = 320,
                plantedLocId = 7993,
                readyLocId = 7999,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.FruitTree,
                seed = "obj.plantpot_orange_sapling",
                seedCount = 1,
                product = "obj.orange",
                displayName = "orange tree",
                level = 39,
                plantXp = 35.5,
                harvestXp = 2470.2,
                minYield = 6,
                maxYield = 6,
                growSeconds = 340,
                plantedLocId = 8051,
                readyLocId = 8057,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.FruitTree,
                seed = "obj.plantpot_curry_sapling",
                seedCount = 1,
                product = "obj.curry_leaf",
                displayName = "curry tree",
                level = 42,
                plantXp = 40.0,
                harvestXp = 2906.9,
                minYield = 6,
                maxYield = 6,
                growSeconds = 360,
                plantedLocId = 8020,
                readyLocId = 8026,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.FruitTree,
                seed = "obj.plantpot_pineapple_sapling",
                seedCount = 1,
                product = "obj.pineapple",
                displayName = "pineapple plant",
                level = 51,
                plantXp = 57.0,
                harvestXp = 4605.7,
                minYield = 6,
                maxYield = 6,
                growSeconds = 380,
                plantedLocId = 7966,
                readyLocId = 7972,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.FruitTree,
                seed = "obj.plantpot_papaya_sapling",
                seedCount = 1,
                product = "obj.papaya",
                displayName = "papaya tree",
                level = 57,
                plantXp = 72.0,
                harvestXp = 6146.6,
                minYield = 6,
                maxYield = 6,
                growSeconds = 400,
                plantedLocId = 8105,
                readyLocId = 8111,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.FruitTree,
                seed = "obj.plantpot_palm_sapling",
                seedCount = 1,
                product = "obj.coconut",
                displayName = "palm tree",
                level = 68,
                plantXp = 110.5,
                harvestXp = 10150.1,
                minYield = 6,
                maxYield = 6,
                growSeconds = 420,
                plantedLocId = 8078,
                readyLocId = 8084,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.FruitTree,
                seed = "obj.plantpot_dragonfruit_sapling",
                seedCount = 1,
                product = "obj.dragonfruit",
                displayName = "dragonfruit tree",
                level = 81,
                plantXp = 140.0,
                harvestXp = 17335.0,
                minYield = 6,
                maxYield = 6,
                growSeconds = 440,
                plantedLocId = 34008,
                readyLocId = 34014,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.HardwoodTree,
                seed = "obj.plantpot_teak_sapling",
                seedCount = 1,
                product = null,
                displayName = "teak tree",
                level = 35,
                plantXp = 35.0,
                harvestXp = 7290.0,
                minYield = 0,
                maxYield = 0,
                growSeconds = 360,
                plantedLocId = 30437,
                readyLocId = 30444,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.HardwoodTree,
                seed = "obj.plantpot_mahogany_sapling",
                seedCount = 1,
                product = null,
                displayName = "mahogany tree",
                level = 55,
                plantXp = 63.0,
                harvestXp = 15720.0,
                minYield = 0,
                maxYield = 0,
                growSeconds = 420,
                plantedLocId = 30406,
                readyLocId = 30416,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Seaweed,
                seed = "obj.seaweed_seed",
                seedCount = 1,
                product = "obj.giant_seaweed",
                displayName = "giant seaweed",
                level = 23,
                plantXp = 19.0,
                harvestXp = 21.0,
                minYield = 3,
                maxYield = 10,
                growSeconds = 120,
                plantedLocId = 30487,
                readyLocId = 30491,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Anima,
                seed = "obj.iasor_seed",
                seedCount = 1,
                product = null,
                displayName = "iasor plant",
                level = 76,
                plantXp = 100.0,
                harvestXp = 0.0,
                minYield = 0,
                maxYield = 0,
                growSeconds = 300,
                plantedLocId = 33984,
                readyLocId = 33988,
                harvestMode = FarmingHarvestMode.CheckHealth,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Anima,
                seed = "obj.attas_seed",
                seedCount = 1,
                product = null,
                displayName = "attas plant",
                level = 76,
                plantXp = 100.0,
                harvestXp = 0.0,
                minYield = 0,
                maxYield = 0,
                growSeconds = 300,
                plantedLocId = 33991,
                readyLocId = 33995,
                harvestMode = FarmingHarvestMode.CheckHealth,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Anima,
                seed = "obj.kronos_seed",
                seedCount = 1,
                product = null,
                displayName = "kronos plant",
                level = 76,
                plantXp = 100.0,
                harvestXp = 0.0,
                minYield = 0,
                maxYield = 0,
                growSeconds = 300,
                plantedLocId = 33999,
                readyLocId = 34003,
                harvestMode = FarmingHarvestMode.CheckHealth,
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Calquat,
                seed = "obj.plantpot_calquat_sapling",
                seedCount = 1,
                product = "obj.calquat_fruit",
                displayName = "calquat tree",
                level = 72,
                plantXp = 129.5,
                harvestXp = 12096.0,
                minYield = 6,
                maxYield = 6,
                growSeconds = 440,
                plantedLocId = 7776,
                readyLocId = 7791,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Celastrus,
                seed = "obj.plantpot_celastrus_tree_sapling",
                seedCount = 1,
                product = "obj.celastrus_wood",
                displayName = "celastrus tree",
                level = 85,
                plantXp = 204.0,
                harvestXp = 14130.0,
                minYield = 3,
                maxYield = 10,
                growSeconds = 460,
                plantedLocId = 33699,
                readyLocId = 33704,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
            FarmingRecipe(
                kind = FarmingPatchKind.Redwood,
                seed = "obj.plantpot_redwood_tree_sapling",
                seedCount = 1,
                product = null,
                displayName = "redwood tree",
                level = 90,
                plantXp = 230.0,
                harvestXp = 22450.0,
                minYield = 0,
                maxYield = 0,
                growSeconds = 480,
                plantedLocId = 34205,
                readyLocId = 34293,
                harvestMode = FarmingHarvestMode.CheckHealth,
                plantTool = SPADE,
                plantToolMessage = "You need a spade to plant saplings.",
                plantItemName = "sapling",
            ),
        )

    val saplingRecipes =
        listOf(
            FarmingSaplingRecipe(
                seed = "obj.acorn",
                pottedSeed = "obj.plantpot_acorn",
                sapling = "obj.plantpot_oak_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.willow_seed",
                pottedSeed = "obj.plantpot_willow_seed",
                sapling = "obj.plantpot_willow_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.maple_seed",
                pottedSeed = "obj.plantpot_maple_seed",
                sapling = "obj.plantpot_maple_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.yew_seed",
                pottedSeed = "obj.plantpot_yew_seed",
                sapling = "obj.plantpot_yew_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.magic_tree_seed",
                pottedSeed = "obj.plantpot_magic_tree_seed",
                sapling = "obj.plantpot_magic_tree_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.apple_tree_seed",
                pottedSeed = "obj.plantpot_apple_seed",
                sapling = "obj.plantpot_apple_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.banana_tree_seed",
                pottedSeed = "obj.plantpot_banana_seed",
                sapling = "obj.plantpot_banana_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.orange_tree_seed",
                pottedSeed = "obj.plantpot_orange_seed",
                sapling = "obj.plantpot_orange_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.curry_tree_seed",
                pottedSeed = "obj.plantpot_curry_seed",
                sapling = "obj.plantpot_curry_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.pineapple_tree_seed",
                pottedSeed = "obj.plantpot_pineapple_seed",
                sapling = "obj.plantpot_pineapple_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.papaya_tree_seed",
                pottedSeed = "obj.plantpot_papaya_seed",
                sapling = "obj.plantpot_papaya_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.palm_tree_seed",
                pottedSeed = "obj.plantpot_palm_seed",
                sapling = "obj.plantpot_palm_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.dragonfruit_tree_seed",
                pottedSeed = "obj.plantpot_dragonfruit_seed",
                sapling = "obj.plantpot_dragonfruit_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.teak_seed",
                pottedSeed = "obj.plantpot_teak_seed",
                sapling = "obj.plantpot_teak_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.mahogany_seed",
                pottedSeed = "obj.plantpot_mahogany_seed",
                sapling = "obj.plantpot_mahogany_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.calquat_tree_seed",
                pottedSeed = "obj.plantpot_calquat_seed",
                sapling = "obj.plantpot_calquat_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.celastrus_tree_seed",
                pottedSeed = "obj.plantpot_celastrus_tree_seed",
                sapling = "obj.plantpot_celastrus_tree_sapling",
            ),
            FarmingSaplingRecipe(
                seed = "obj.redwood_tree_seed",
                pottedSeed = "obj.plantpot_redwood_tree_seed",
                sapling = "obj.plantpot_redwood_tree_sapling",
            ),
        )

    val saplingRecipeBySeed = saplingRecipes.associateBy { it.seed }
    val saplingRecipeByPottedSeed = saplingRecipes.associateBy { it.pottedSeed }

    val recipeBySeed = recipes.associateBy { it.seed }
    val recipeByPlantedLoc = recipes.associateBy { it.plantedLocId }
    val recipeByReadyLoc = recipes.associateBy { it.readyLocId }
    val recipeByIndex = recipes.withIndex().associate { it.index to it.value }
    val recipeIndex = recipes.withIndex().associate { it.value to it.index }

    val cleanLocKind =
        FarmingPatchKind.entries.flatMap { kind -> kind.cleanLocIds.map { it to kind } }.toMap()

    val trackedLocIds =
        cleanLocKind.keys +
            recipeByPlantedLoc.keys +
            recipeByReadyLoc.keys +
            intArrayOf(15063, 15064, 15065, 15066, 18847, 18848, 18849).toSet()

    val weedProgression =
        mapOf(
            15063 to 15064,
            15064 to 15065,
            15065 to 15066,
            18847 to 18848,
            18848 to 18849,
            18849 to 18818,
        )

    val weedCleanKind =
        mapOf(
            15066 to FarmingPatchKind.Herb,
            18818 to FarmingPatchKind.Herb,
        )
}
