package org.rsmod.content.skills.agility

import dev.openrune.rscm.RSCM
import dev.openrune.rscm.RSCMType
import kotlin.math.abs
import org.rsmod.api.config.constants
import org.rsmod.map.CoordGrid

internal object AgilityExtraCourses {
    private val climbAnim: String = seq(CLIMB_ANIM)
    private val jumpAnim: String = seq(JUMP_ANIM)
    private val ropeSwingAnim: String = seq(ROPE_SWING_ANIM)

    private val alKharidRooftopCourse =
        AgilityCourse(
            key = "al_kharid_rooftop",
            name = "Al Kharid Rooftop Course",
            obstacleCount = 8,
            lapXp = 0.0,
            stepAttr = AL_KHARID_ROOFTOP_COURSE_STEP_ATTR,
            lapsAttr = AL_KHARID_ROOFTOP_LAPS_ATTR,
        )

    private val varrockRooftopCourse =
        AgilityCourse(
            key = "varrock_rooftop",
            name = "Varrock Rooftop Course",
            obstacleCount = 9,
            lapXp = 0.0,
            stepAttr = VARROCK_ROOFTOP_COURSE_STEP_ATTR,
            lapsAttr = VARROCK_ROOFTOP_LAPS_ATTR,
        )

    private val canifisRooftopCourse =
        AgilityCourse(
            key = "canifis_rooftop",
            name = "Canifis Rooftop Course",
            obstacleCount = 8,
            lapXp = 0.0,
            stepAttr = CANIFIS_ROOFTOP_COURSE_STEP_ATTR,
            lapsAttr = CANIFIS_ROOFTOP_LAPS_ATTR,
        )

    private val faladorRooftopCourse =
        AgilityCourse(
            key = "falador_rooftop",
            name = "Falador Rooftop Course",
            obstacleCount = 13,
            lapXp = 0.0,
            stepAttr = FALADOR_ROOFTOP_COURSE_STEP_ATTR,
            lapsAttr = FALADOR_ROOFTOP_LAPS_ATTR,
        )

    private val seersRooftopCourse =
        AgilityCourse(
            key = "seers_rooftop",
            name = "Seers' Village Rooftop Course",
            obstacleCount = 6,
            lapXp = 0.0,
            stepAttr = SEERS_ROOFTOP_COURSE_STEP_ATTR,
            lapsAttr = SEERS_ROOFTOP_LAPS_ATTR,
        )

    private val pollnivneachRooftopCourse =
        AgilityCourse(
            key = "pollnivneach_rooftop",
            name = "Pollnivneach Rooftop Course",
            obstacleCount = 9,
            lapXp = 0.0,
            stepAttr = POLLNIVNEACH_ROOFTOP_COURSE_STEP_ATTR,
            lapsAttr = POLLNIVNEACH_ROOFTOP_LAPS_ATTR,
        )

    private val rellekkaRooftopCourse =
        AgilityCourse(
            key = "rellekka_rooftop",
            name = "Rellekka Rooftop Course",
            obstacleCount = 7,
            lapXp = 0.0,
            stepAttr = RELLEKKA_ROOFTOP_COURSE_STEP_ATTR,
            lapsAttr = RELLEKKA_ROOFTOP_LAPS_ATTR,
        )

    private val ardougneRooftopCourse =
        AgilityCourse(
            key = "ardougne_rooftop",
            name = "Ardougne Rooftop Course",
            obstacleCount = 7,
            lapXp = 0.0,
            stepAttr = ARDOUGNE_ROOFTOP_COURSE_STEP_ATTR,
            lapsAttr = ARDOUGNE_ROOFTOP_LAPS_ATTR,
        )

    private val prifddinasRooftopCourse =
        AgilityCourse(
            key = "prifddinas_rooftop",
            name = "Prifddinas Agility Course",
            obstacleCount = 12,
            lapXp = 0.0,
            stepAttr = PRIFDDINAS_ROOFTOP_COURSE_STEP_ATTR,
            lapsAttr = PRIFDDINAS_ROOFTOP_LAPS_ATTR,
        )

    private val wildernessCourse =
        AgilityCourse(
            key = "wilderness",
            name = "Wilderness Agility Course",
            obstacleCount = 5,
            lapXp = 0.0,
            stepAttr = WILDERNESS_COURSE_STEP_ATTR,
            lapsAttr = WILDERNESS_LAPS_ATTR,
        )

    private val apeAtollCourse =
        AgilityCourse(
            key = "ape_atoll",
            name = "Ape Atoll Agility Course",
            obstacleCount = 6,
            lapXp = 0.0,
            stepAttr = APE_ATOLL_COURSE_STEP_ATTR,
            lapsAttr = APE_ATOLL_LAPS_ATTR,
        )

    val obstacles: List<AgilityObstacle> =
        listOf(
            obstacle(
                course = alKharidRooftopCourse,
                step = 1,
                locs = intArrayOf(11633),
                level = 20,
                xp = 10.0,
                start = tile(3273, 3195, 0),
                end = tile(3273, 3192, 3),
                anim = climbAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = alKharidRooftopCourse,
                step = 2,
                locs = intArrayOf(14398),
                level = 20,
                xp = 30.0,
                start = tile(3272, 3182, 3),
                end = tile(3272, 3172, 3),
                path = listOf(tile(3272, 3172, 3)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = alKharidRooftopCourse,
                step = 3,
                locs = intArrayOf(14402),
                level = 20,
                xp = 40.0,
                start = tile(3269, 3166, 3),
                end = tile(3284, 3166, 3),
                anim = ropeSwingAnim,
                delay = 3,
                exactMoveDelay = 95,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = alKharidRooftopCourse,
                step = 4,
                locs = intArrayOf(14403),
                level = 20,
                xp = 40.0,
                start = tile(3303, 3163, 1),
                end = tile(3315, 3163, 1),
                path = listOf(tile(3315, 3163, 1)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = alKharidRooftopCourse,
                step = 5,
                locs = intArrayOf(14404),
                level = 20,
                xp = 10.0,
                start = tile(3318, 3165, 1),
                end = tile(3317, 3174, 2),
                anim = jumpAnim,
                delay = 3,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = alKharidRooftopCourse,
                step = 6,
                locs = intArrayOf(11634),
                level = 20,
                xp = 5.0,
                start = tile(3317, 3179, 2),
                end = tile(3316, 3180, 3),
                anim = climbAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = alKharidRooftopCourse,
                step = 7,
                locs = intArrayOf(14409),
                level = 20,
                xp = 15.0,
                start = tile(3314, 3186, 3),
                end = tile(3302, 3187, 3),
                path = listOf(tile(3302, 3186, 3), tile(3302, 3187, 3)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = alKharidRooftopCourse,
                step = 8,
                locs = intArrayOf(14399),
                level = 20,
                xp = 30.0,
                start = tile(3302, 3189, 3),
                end = tile(3299, 3194, 0),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = varrockRooftopCourse,
                step = 1,
                locs = intArrayOf(14412),
                level = 30,
                xp = 12.0,
                start = tile(3221, 3414, 0),
                end = tile(3219, 3414, 3),
                anim = climbAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = varrockRooftopCourse,
                step = 2,
                locs = intArrayOf(14413),
                level = 30,
                xp = 21.0,
                start = tile(3214, 3414, 3),
                end = tile(3208, 3414, 3),
                anim = ropeSwingAnim,
                exactMoveDelay = 75,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = varrockRooftopCourse,
                step = 3,
                locs = intArrayOf(14414),
                level = 30,
                xp = 17.0,
                start = tile(3201, 3416, 3),
                end = tile(3197, 3416, 1),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = varrockRooftopCourse,
                step = 4,
                locs = intArrayOf(14832),
                level = 30,
                xp = 25.0,
                start = tile(3194, 3416, 1),
                end = tile(3192, 3406, 3),
                path = listOf(tile(3190, 3414, 1), tile(3190, 3407, 1), tile(3192, 3406, 3)),
                movement = AgilityMovement.BalanceWalk,
            ),
            obstacle(
                course = varrockRooftopCourse,
                step = 5,
                locs = intArrayOf(14833),
                level = 30,
                xp = 9.0,
                start = tile(3192, 3402, 3),
                end = tile(3192, 3398, 3),
                anim = jumpAnim,
                exactMoveDelay = 60,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = varrockRooftopCourse,
                step = 6,
                locs = intArrayOf(14834),
                level = 30,
                xp = 22.0,
                start = tile(3208, 3397, 3),
                end = tile(3218, 3399, 3),
                anim = jumpAnim,
                exactMoveDelay = 85,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = varrockRooftopCourse,
                step = 7,
                locs = intArrayOf(14835),
                level = 30,
                xp = 4.0,
                start = tile(3232, 3402, 3),
                end = tile(3236, 3403, 3),
                anim = jumpAnim,
                exactMoveDelay = 60,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = varrockRooftopCourse,
                step = 8,
                locs = intArrayOf(14836),
                level = 30,
                xp = 3.0,
                start = tile(3236, 3404, 3),
                end = tile(3236, 3410, 3),
                anim = jumpAnim,
                exactMoveDelay = 75,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = varrockRooftopCourse,
                step = 9,
                locs = intArrayOf(14841),
                level = 30,
                xp = 125.0,
                start = tile(3236, 3415, 3),
                end = tile(3236, 3417, 0),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = canifisRooftopCourse,
                step = 1,
                locs = intArrayOf(14843),
                level = 40,
                xp = 10.0,
                start = tile(3507, 3488, 0),
                end = tile(3506, 3492, 2),
                anim = climbAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = canifisRooftopCourse,
                step = 2,
                locs = intArrayOf(14844),
                level = 40,
                xp = 8.0,
                start = tile(3505, 3498, 2),
                end = tile(3502, 3504, 2),
                anim = jumpAnim,
                exactMoveDelay = 75,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = canifisRooftopCourse,
                step = 3,
                locs = intArrayOf(14845),
                level = 40,
                xp = 8.0,
                start = tile(3498, 3504, 2),
                end = tile(3493, 3504, 2),
                anim = jumpAnim,
                exactMoveDelay = 65,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = canifisRooftopCourse,
                step = 4,
                locs = intArrayOf(14848),
                level = 40,
                xp = 10.0,
                start = tile(3487, 3499, 2),
                end = tile(3479, 3499, 3),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = canifisRooftopCourse,
                step = 5,
                locs = intArrayOf(14846),
                level = 40,
                xp = 8.0,
                start = tile(3478, 3493, 3),
                end = tile(3478, 3486, 2),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = canifisRooftopCourse,
                step = 6,
                locs = intArrayOf(14894),
                level = 40,
                xp = 10.0,
                start = tile(3481, 3482, 2),
                end = tile(3489, 3476, 3),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = canifisRooftopCourse,
                step = 7,
                locs = intArrayOf(14847),
                level = 40,
                xp = 11.0,
                start = tile(3502, 3476, 3),
                end = tile(3510, 3476, 2),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = canifisRooftopCourse,
                step = 8,
                locs = intArrayOf(14897),
                level = 40,
                xp = 175.0,
                start = tile(3510, 3480, 2),
                end = tile(3510, 3485, 0),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = faladorRooftopCourse,
                step = 1,
                locs = intArrayOf(14898),
                level = 50,
                xp = 8.0,
                start = tile(3036, 3341, 0),
                end = tile(3036, 3342, 3),
                anim = climbAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = faladorRooftopCourse,
                step = 2,
                locs = intArrayOf(14899),
                level = 50,
                xp = 17.0,
                start = tile(3036, 3343, 3),
                end = tile(3047, 3343, 3),
                path = listOf(tile(3047, 3343, 3)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = faladorRooftopCourse,
                step = 3,
                locs = intArrayOf(14901),
                level = 50,
                xp = 45.0,
                start = tile(3048, 3347, 3),
                end = tile(3050, 3357, 3),
                path = listOf(tile(3050, 3351, 3), tile(3050, 3357, 3)),
                movement = AgilityMovement.BalanceWalk,
            ),
            obstacle(
                course = faladorRooftopCourse,
                step = 4,
                locs = intArrayOf(14903),
                level = 50,
                xp = 20.0,
                start = tile(3048, 3358, 3),
                end = tile(3048, 3361, 3),
                anim = jumpAnim,
                exactMoveDelay = 55,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = faladorRooftopCourse,
                step = 5,
                locs = intArrayOf(14904),
                level = 50,
                xp = 20.0,
                start = tile(3045, 3361, 3),
                end = tile(3041, 3361, 3),
                anim = jumpAnim,
                exactMoveDelay = 60,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = faladorRooftopCourse,
                step = 6,
                locs = intArrayOf(14905),
                level = 50,
                xp = 45.0,
                start = tile(3041, 3361, 3),
                end = tile(3028, 3354, 3),
                path = listOf(tile(3033, 3361, 3), tile(3028, 3356, 3), tile(3028, 3354, 3)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = faladorRooftopCourse,
                step = 7,
                locs = intArrayOf(14911),
                level = 50,
                xp = 40.0,
                start = tile(3026, 3353, 3),
                end = tile(3020, 3353, 3),
                path = listOf(tile(3020, 3353, 3)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = faladorRooftopCourse,
                step = 8,
                locs = intArrayOf(14919),
                level = 50,
                xp = 25.0,
                start = tile(3016, 3353, 3),
                end = tile(3016, 3349, 3),
                anim = jumpAnim,
                exactMoveDelay = 60,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = faladorRooftopCourse,
                step = 9,
                locs = intArrayOf(14920),
                level = 50,
                xp = 10.0,
                start = tile(3016, 3349, 3),
                end = tile(3014, 3349, 3),
                anim = jumpAnim,
                exactMoveDelay = 45,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = faladorRooftopCourse,
                step = 10,
                locs = intArrayOf(14921),
                level = 50,
                xp = 10.0,
                start = tile(3014, 3349, 3),
                end = tile(3014, 3347, 3),
                anim = jumpAnim,
                exactMoveDelay = 45,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = faladorRooftopCourse,
                step = 11,
                locs = intArrayOf(14922),
                level = 50,
                xp = 10.0,
                start = tile(3014, 3347, 3),
                end = tile(3014, 3345, 3),
                anim = jumpAnim,
                exactMoveDelay = 45,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = faladorRooftopCourse,
                step = 12,
                locs = intArrayOf(14924),
                level = 50,
                xp = 10.0,
                start = tile(3014, 3345, 3),
                end = tile(3016, 3345, 3),
                anim = jumpAnim,
                exactMoveDelay = 45,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = faladorRooftopCourse,
                step = 13,
                locs = intArrayOf(14925),
                level = 50,
                xp = 180.0,
                start = tile(3016, 3345, 3),
                end = tile(3029, 3333, 0),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = seersRooftopCourse,
                step = 1,
                locs = intArrayOf(14927),
                level = 60,
                xp = 45.0,
                start = tile(2729, 3488, 0),
                end = tile(2729, 3491, 3),
                anim = climbAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = seersRooftopCourse,
                step = 2,
                locs = intArrayOf(14928),
                level = 60,
                xp = 20.0,
                start = tile(2729, 3491, 3),
                end = tile(2713, 3494, 2),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = seersRooftopCourse,
                step = 3,
                locs = intArrayOf(14932),
                level = 60,
                xp = 20.0,
                start = tile(2713, 3494, 2),
                end = tile(2710, 3481, 2),
                path = listOf(tile(2710, 3481, 2)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = seersRooftopCourse,
                step = 4,
                locs = intArrayOf(14929),
                level = 60,
                xp = 35.0,
                start = tile(2710, 3481, 2),
                end = tile(2710, 3472, 3),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = seersRooftopCourse,
                step = 5,
                locs = intArrayOf(14930),
                level = 60,
                xp = 15.0,
                start = tile(2710, 3472, 3),
                end = tile(2702, 3465, 2),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = seersRooftopCourse,
                step = 6,
                locs = intArrayOf(14931),
                level = 60,
                xp = 435.0,
                start = tile(2702, 3465, 2),
                end = tile(2704, 3464, 0),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = pollnivneachRooftopCourse,
                step = 1,
                locs = intArrayOf(14935),
                level = 70,
                xp = 10.0,
                start = tile(3351, 2963, 0),
                end = tile(3351, 2964, 1),
                anim = climbAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = pollnivneachRooftopCourse,
                step = 2,
                locs = intArrayOf(14936),
                level = 70,
                xp = 45.0,
                start = tile(3350, 2968, 1),
                end = tile(3352, 2973, 1),
                anim = jumpAnim,
                exactMoveDelay = 65,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = pollnivneachRooftopCourse,
                step = 3,
                locs = intArrayOf(14937),
                level = 70,
                xp = 65.0,
                start = tile(3355, 2976, 1),
                end = tile(3360, 2978, 1),
                anim = ropeSwingAnim,
                exactMoveDelay = 70,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = pollnivneachRooftopCourse,
                step = 4,
                locs = intArrayOf(14938),
                level = 70,
                xp = 35.0,
                start = tile(3362, 2977, 1),
                end = tile(3366, 2976, 1),
                anim = jumpAnim,
                exactMoveDelay = 60,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = pollnivneachRooftopCourse,
                step = 5,
                locs = intArrayOf(14939),
                level = 70,
                xp = 75.0,
                start = tile(3367, 2976, 1),
                end = tile(3365, 2981, 1),
                anim = ropeSwingAnim,
                exactMoveDelay = 70,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = pollnivneachRooftopCourse,
                step = 6,
                locs = intArrayOf(14940),
                level = 70,
                xp = 5.0,
                start = tile(3365, 2981, 1),
                end = tile(3365, 2983, 2),
                anim = climbAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = pollnivneachRooftopCourse,
                step = 7,
                locs = intArrayOf(14941),
                level = 70,
                xp = 55.0,
                start = tile(3365, 2983, 2),
                end = tile(3365, 2990, 2),
                path = listOf(tile(3365, 2990, 2)),
                movement = AgilityMovement.BalanceWalk,
            ),
            obstacle(
                course = pollnivneachRooftopCourse,
                step = 8,
                locs = intArrayOf(14944),
                level = 70,
                xp = 70.0,
                start = tile(3359, 2995, 2),
                end = tile(3359, 3000, 2),
                anim = jumpAnim,
                exactMoveDelay = 65,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = pollnivneachRooftopCourse,
                step = 9,
                locs = intArrayOf(14945),
                level = 70,
                xp = 540.0,
                start = tile(3362, 3002, 2),
                end = tile(3364, 2998, 0),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = rellekkaRooftopCourse,
                step = 1,
                locs = intArrayOf(14946),
                level = 80,
                xp = 20.0,
                start = tile(2625, 3677, 0),
                end = tile(2626, 3676, 3),
                anim = climbAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = rellekkaRooftopCourse,
                step = 2,
                locs = intArrayOf(14947),
                level = 80,
                xp = 30.0,
                start = tile(2626, 3676, 3),
                end = tile(2622, 3672, 3),
                anim = jumpAnim,
                exactMoveDelay = 65,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = rellekkaRooftopCourse,
                step = 3,
                locs = intArrayOf(14987),
                level = 80,
                xp = 40.0,
                start = tile(2622, 3672, 3),
                end = tile(2627, 3654, 3),
                path = listOf(tile(2626, 3654, 3), tile(2627, 3654, 3)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = rellekkaRooftopCourse,
                step = 4,
                locs = intArrayOf(14990),
                level = 80,
                xp = 85.0,
                start = tile(2627, 3654, 3),
                end = tile(2639, 3653, 3),
                path = listOf(tile(2635, 3658, 3), tile(2639, 3654, 3), tile(2639, 3653, 3)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = rellekkaRooftopCourse,
                step = 5,
                locs = intArrayOf(14991),
                level = 80,
                xp = 25.0,
                start = tile(2639, 3653, 3),
                end = tile(2643, 3657, 3),
                anim = jumpAnim,
                exactMoveDelay = 65,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = rellekkaRooftopCourse,
                step = 6,
                locs = intArrayOf(14992),
                level = 80,
                xp = 105.0,
                start = tile(2643, 3657, 3),
                end = tile(2655, 3670, 3),
                path = listOf(tile(2647, 3663, 3), tile(2654, 3670, 3), tile(2655, 3670, 3)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = rellekkaRooftopCourse,
                step = 7,
                locs = intArrayOf(14994),
                level = 80,
                xp = 475.0,
                start = tile(2655, 3670, 3),
                end = tile(2653, 3676, 0),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = ardougneRooftopCourse,
                step = 1,
                locs = intArrayOf(15608),
                level = 90,
                xp = 43.0,
                start = tile(2673, 3296, 0),
                end = tile(2671, 3299, 3),
                anim = climbAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = ardougneRooftopCourse,
                step = 2,
                locs = intArrayOf(15609),
                level = 90,
                xp = 65.0,
                start = tile(2671, 3299, 3),
                end = tile(2665, 3318, 3),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = ardougneRooftopCourse,
                step = 3,
                locs = intArrayOf(26635),
                level = 90,
                xp = 50.0,
                start = tile(2665, 3318, 3),
                end = tile(2656, 3318, 3),
                path = listOf(tile(2656, 3318, 3)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = ardougneRooftopCourse,
                step = 4,
                locs = intArrayOf(15610),
                level = 90,
                xp = 21.0,
                start = tile(2656, 3318, 3),
                end = tile(2653, 3314, 3),
                anim = jumpAnim,
                exactMoveDelay = 60,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = ardougneRooftopCourse,
                step = 5,
                locs = intArrayOf(15611),
                level = 90,
                xp = 28.0,
                start = tile(2653, 3314, 3),
                end = tile(2651, 3309, 3),
                anim = jumpAnim,
                exactMoveDelay = 65,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = ardougneRooftopCourse,
                step = 6,
                locs = intArrayOf(28912),
                level = 90,
                xp = 57.0,
                start = tile(2651, 3309, 3),
                end = tile(2656, 3297, 3),
                path = listOf(tile(2654, 3299, 3), tile(2656, 3297, 3)),
                movement = AgilityMovement.BalanceWalk,
            ),
            obstacle(
                course = ardougneRooftopCourse,
                step = 7,
                locs = intArrayOf(15612),
                level = 90,
                xp = 529.0,
                start = tile(2656, 3297, 3),
                end = tile(2668, 3297, 0),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = prifddinasRooftopCourse,
                step = 1,
                locs = intArrayOf(36221),
                level = 75,
                xp = 11.5,
                start = tile(3254, 6109, 0),
                end = tile(3255, 6109, 2),
                anim = climbAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = prifddinasRooftopCourse,
                step = 2,
                locs = intArrayOf(36225),
                level = 75,
                xp = 30.7,
                start = tile(3258, 6105, 2),
                end = tile(3272, 6105, 2),
                path = listOf(tile(3272, 6105, 2)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = prifddinasRooftopCourse,
                step = 3,
                locs = intArrayOf(36227),
                level = 75,
                xp = 28.1,
                start = tile(3273, 6105, 2),
                end = tile(3269, 6112, 2),
                anim = jumpAnim,
                exactMoveDelay = 75,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = prifddinasRooftopCourse,
                step = 4,
                locs = intArrayOf(36228),
                level = 75,
                xp = 23.0,
                start = tile(3269, 6112, 2),
                end = tile(3269, 6117, 0),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = prifddinasRooftopCourse,
                step = 5,
                locs = intArrayOf(36229),
                level = 75,
                xp = 11.5,
                start = tile(3269, 6117, 0),
                end = tile(3293, 6141, 0),
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = prifddinasRooftopCourse,
                step = 6,
                locs = intArrayOf(36231),
                level = 75,
                xp = 0.0,
                start = tile(3293, 6141, 0),
                end = tile(3293, 6145, 2),
                anim = climbAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = prifddinasRooftopCourse,
                step = 7,
                locs = intArrayOf(36233),
                level = 75,
                xp = 25.6,
                start = tile(3293, 6145, 2),
                end = tile(3281, 6142, 2),
                path = listOf(tile(3281, 6142, 2)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = prifddinasRooftopCourse,
                step = 8,
                locs = intArrayOf(36234),
                level = 75,
                xp = 30.7,
                start = tile(3281, 6142, 2),
                end = tile(3271, 6149, 2),
                path = listOf(tile(3277, 6143, 2), tile(3271, 6149, 2)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = prifddinasRooftopCourse,
                step = 9,
                locs = intArrayOf(36235),
                level = 75,
                xp = 25.6,
                start = tile(3271, 6149, 2),
                end = tile(3270, 6158, 2),
                path = listOf(tile(3270, 6158, 2)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = prifddinasRooftopCourse,
                step = 10,
                locs = intArrayOf(36236),
                level = 75,
                xp = 30.7,
                start = tile(3270, 6158, 2),
                end = tile(3274, 6168, 2),
                path = listOf(tile(3274, 6168, 2)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = prifddinasRooftopCourse,
                step = 11,
                locs = intArrayOf(36237),
                level = 75,
                xp = 30.7,
                start = tile(3274, 6168, 2),
                end = tile(3284, 6177, 0),
                anim = jumpAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = prifddinasRooftopCourse,
                step = 12,
                locs = intArrayOf(36238),
                level = 75,
                xp = 1037.1,
                start = tile(3284, 6177, 0),
                end = tile(3240, 6109, 0),
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = wildernessCourse,
                step = 1,
                locs = intArrayOf(23137),
                locCoords = coords(tile(3004, 3938, 0)),
                level = 52,
                xp = 12.5,
                start = tile(3004, 3937, 0),
                end = tile(3004, 3950, 0),
                anim = AgilityData.pipeAnim,
                animReplayInterval = 2,
                delay = 8,
                exactMoveDelay = 220,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = wildernessCourse,
                step = 2,
                locs = intArrayOf(23132),
                level = 52,
                xp = 20.0,
                start = tile(3005, 3953, 0),
                end = tile(3005, 3958, 0),
                anim = ropeSwingAnim,
                exactMoveDelay = 70,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = wildernessCourse,
                step = 3,
                locs = intArrayOf(23556),
                level = 52,
                xp = 20.0,
                start = tile(3002, 3960, 0),
                end = tile(2996, 3960, 0),
                anim = jumpAnim,
                exactMoveDelay = 80,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = wildernessCourse,
                step = 4,
                locs = intArrayOf(23542),
                level = 52,
                xp = 20.0,
                start = tile(3002, 3945, 0),
                end = tile(2994, 3945, 0),
                path = listOf(tile(2994, 3945, 0)),
                movement = AgilityMovement.StraightWalk,
            ),
            obstacle(
                course = wildernessCourse,
                step = 5,
                locs = intArrayOf(23640),
                level = 52,
                xp = 498.9,
                start = tile(2993, 3937, 0),
                end = tile(2993, 3933, 0),
                anim = climbAnim,
                exactMoveDelay = 60,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = apeAtollCourse,
                step = 1,
                locs = intArrayOf(12568),
                level = 48,
                xp = 40.0,
                start = tile(2756, 2742, 0),
                end = tile(2753, 2742, 0),
                anim = jumpAnim,
                exactMoveDelay = 55,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = apeAtollCourse,
                step = 2,
                locs = intArrayOf(12570),
                level = 48,
                xp = 40.0,
                start = tile(2753, 2742, 0),
                end = tile(2753, 2742, 2),
                anim = climbAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = apeAtollCourse,
                step = 3,
                locs = intArrayOf(12573, 12575),
                level = 48,
                xp = 40.0,
                start = tile(2752, 2741, 2),
                end = tile(2747, 2741, 0),
                anim = ropeSwingAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            obstacle(
                course = apeAtollCourse,
                step = 4,
                locs = intArrayOf(12576),
                level = 48,
                xp = 60.0,
                start = tile(2746, 2741, 0),
                end = tile(2742, 2741, 0),
                path = listOf(tile(2742, 2741, 0)),
                movement = AgilityMovement.BalanceWalk,
            ),
            obstacle(
                course = apeAtollCourse,
                step = 5,
                locs = intArrayOf(12578),
                level = 48,
                xp = 100.0,
                start = tile(2751, 2731, 0),
                end = tile(2756, 2731, 0),
                anim = ropeSwingAnim,
                exactMoveDelay = 70,
                movement = AgilityMovement.ExactMove,
            ),
            obstacle(
                course = apeAtollCourse,
                step = 6,
                locs = intArrayOf(12618),
                level = 48,
                xp = 300.0,
                start = tile(2758, 2735, 0),
                end = tile(2770, 2747, 0),
                anim = climbAnim,
                delay = 2,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
        )

    private fun obstacle(
        course: AgilityCourse,
        step: Int,
        locs: IntArray,
        level: Int,
        xp: Double,
        start: CoordGrid,
        end: CoordGrid,
        movement: AgilityMovement,
        locCoords: Set<CoordGrid> = emptySet(),
        path: List<CoordGrid> = emptyList(),
        anim: String? = null,
        animReplayInterval: Int? = null,
        waitForArrival: Boolean = true,
        delay: Int = defaultDelay(movement),
        exactMoveDelay: Int = defaultExactMoveDelay(start, end, movement),
        faceDir: Int = face(start, end),
    ): AgilityObstacle =
        AgilityObstacle(
            course = course,
            step = step,
            locs = locs,
            locCoords = locCoords,
            level = level,
            xp = xp,
            start = start,
            end = end,
            path = path,
            anim = anim,
            animReplayInterval = animReplayInterval,
            waitForArrival = waitForArrival,
            delay = delay,
            exactMoveDelay = exactMoveDelay,
            faceDir = faceDir,
            movement = movement,
        )

    private fun defaultDelay(movement: AgilityMovement): Int =
        if (movement == AgilityMovement.TelejumpAfterDelay) 2 else 0

    private fun defaultExactMoveDelay(
        start: CoordGrid,
        end: CoordGrid,
        movement: AgilityMovement,
    ): Int {
        if (movement != AgilityMovement.ExactMove) {
            return 0
        }
        val distance = maxOf(abs(end.x - start.x), abs(end.z - start.z))
        return maxOf(45, distance * 15)
    }

    private fun face(start: CoordGrid, end: CoordGrid): Int {
        val xDiff = end.x - start.x
        val zDiff = end.z - start.z
        if (abs(xDiff) >= abs(zDiff) && xDiff != 0) {
            return if (xDiff > 0) constants.em_face_east else constants.em_face_west
        }
        return if (zDiff >= 0) constants.em_face_north else constants.em_face_south
    }

    private fun tile(x: Int, z: Int, level: Int): CoordGrid = CoordGrid(x, z, level)

    private fun coords(coord: CoordGrid): Set<CoordGrid> = setOf(coord)

    private fun seq(id: Int): String =
        RSCM.getReverseMapping(RSCMType.SEQ, id) ?: error("Missing agility seq: $id")

    private const val CLIMB_ANIM: Int = 828
    private const val JUMP_ANIM: Int = 2586
    private const val ROPE_SWING_ANIM: Int = 751
}
