package org.rsmod.content.skills.agility

import dev.openrune.rscm.RSCM
import dev.openrune.rscm.RSCMType
import org.rsmod.api.attr.AttributeKey
import org.rsmod.api.config.constants
import org.rsmod.map.CoordGrid

internal data class AgilityCourse(
    val key: String,
    val name: String,
    val obstacleCount: Int,
    val lapXp: Double,
    val stepAttr: AttributeKey<Int>,
    val lapsAttr: AttributeKey<Int>,
)

internal data class AgilityObstacle(
    val course: AgilityCourse,
    val step: Int,
    val locs: IntArray,
    val locCoords: Set<CoordGrid> = emptySet(),
    val level: Int,
    val xp: Double,
    val start: CoordGrid,
    val end: CoordGrid,
    val path: List<CoordGrid> = emptyList(),
    val anim: String?,
    val animReplayInterval: Int? = null,
    val waitForArrival: Boolean = true,
    val delay: Int,
    val exactMoveDelay: Int,
    val faceDir: Int,
    val movement: AgilityMovement,
)

internal enum class AgilityMovement {
    ExactMove,
    StraightWalk,
    BalanceWalk,
    TelejumpAfterDelay,
}

internal object AgilityData {
    val pipeAnim: String = seq(PIPE_ANIM)

    val gnomeStrongholdCourse =
        AgilityCourse(
            key = "gnome_stronghold",
            name = "Gnome Stronghold Agility Course",
            obstacleCount = 7,
            lapXp = 39.5,
            stepAttr = GNOME_STRONGHOLD_COURSE_STEP_ATTR,
            lapsAttr = GNOME_STRONGHOLD_LAPS_ATTR,
        )

    val barbarianOutpostCourse =
        AgilityCourse(
            key = "barbarian_outpost",
            name = "Barbarian Outpost Agility Course",
            obstacleCount = 7,
            lapXp = 46.2,
            stepAttr = BARBARIAN_OUTPOST_COURSE_STEP_ATTR,
            lapsAttr = BARBARIAN_OUTPOST_LAPS_ATTR,
        )

    val draynorRooftopCourse =
        AgilityCourse(
            key = "draynor_rooftop",
            name = "Draynor Village Rooftop Course",
            obstacleCount = 7,
            lapXp = 0.0,
            stepAttr = DRAYNOR_ROOFTOP_COURSE_STEP_ATTR,
            lapsAttr = DRAYNOR_ROOFTOP_LAPS_ATTR,
        )

    val obstacles =
        listOf(
            AgilityObstacle(
                course = gnomeStrongholdCourse,
                step = 1,
                locs = intArrayOf(23145),
                level = 1,
                xp = 7.5,
                start = CoordGrid(2474, 3436, 0),
                end = CoordGrid(2474, 3429, 0),
                anim = null,
                delay = 7,
                exactMoveDelay = 0,
                faceDir = constants.em_face_south,
                movement = AgilityMovement.StraightWalk,
            ),
            AgilityObstacle(
                course = gnomeStrongholdCourse,
                step = 2,
                locs = intArrayOf(23134),
                level = 1,
                xp = 7.5,
                start = CoordGrid(2473, 3425, 0),
                end = CoordGrid(2473, 3425, 1),
                anim = "seq.human_reachforladder",
                delay = 2,
                exactMoveDelay = 0,
                faceDir = constants.em_face_north,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            AgilityObstacle(
                course = gnomeStrongholdCourse,
                step = 3,
                locs = intArrayOf(23559),
                level = 1,
                xp = 5.0,
                start = CoordGrid(2473, 3422, 1),
                end = CoordGrid(2473, 3420, 2),
                anim = "seq.human_reachforladder",
                delay = 2,
                exactMoveDelay = 0,
                faceDir = constants.em_face_north,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            AgilityObstacle(
                course = gnomeStrongholdCourse,
                step = 4,
                locs = intArrayOf(23557),
                level = 1,
                xp = 7.5,
                start = CoordGrid(2477, 3420, 2),
                end = CoordGrid(2483, 3420, 2),
                anim = null,
                delay = 6,
                exactMoveDelay = 0,
                faceDir = constants.em_face_east,
                movement = AgilityMovement.StraightWalk,
            ),
            AgilityObstacle(
                course = gnomeStrongholdCourse,
                step = 5,
                locs = intArrayOf(23560),
                level = 1,
                xp = 5.0,
                start = CoordGrid(2485, 3420, 2),
                end = CoordGrid(2485, 3421, 0),
                anim = "seq.human_reachforladder",
                delay = 2,
                exactMoveDelay = 0,
                faceDir = constants.em_face_south,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            AgilityObstacle(
                course = gnomeStrongholdCourse,
                step = 6,
                locs = intArrayOf(23135),
                level = 1,
                xp = 7.5,
                start = CoordGrid(2486, 3425, 0),
                end = CoordGrid(2486, 3427, 0),
                anim = "seq.human_reachforladder",
                delay = 2,
                exactMoveDelay = 60,
                faceDir = constants.em_face_north,
                movement = AgilityMovement.ExactMove,
            ),
            AgilityObstacle(
                course = gnomeStrongholdCourse,
                step = 7,
                locs = intArrayOf(23138),
                level = 1,
                xp = 7.5,
                start = CoordGrid(2484, 3430, 0),
                end = CoordGrid(2484, 3437, 0),
                anim = pipeAnim,
                animReplayInterval = 2,
                delay = 6,
                exactMoveDelay = 180,
                faceDir = constants.em_face_north,
                movement = AgilityMovement.ExactMove,
            ),
            AgilityObstacle(
                course = gnomeStrongholdCourse,
                step = 7,
                locs = intArrayOf(23139),
                level = 1,
                xp = 7.5,
                start = CoordGrid(2487, 3430, 0),
                end = CoordGrid(2487, 3437, 0),
                anim = pipeAnim,
                animReplayInterval = 2,
                delay = 6,
                exactMoveDelay = 180,
                faceDir = constants.em_face_north,
                movement = AgilityMovement.ExactMove,
            ),
            AgilityObstacle(
                course = barbarianOutpostCourse,
                step = 1,
                locs = intArrayOf(23131),
                locCoords = setOf(CoordGrid(2551, 3550, 0)),
                level = 35,
                xp = 22.0,
                start = CoordGrid(2551, 3554, 0),
                end = CoordGrid(2551, 3549, 0),
                anim = seq(ROPE_SWING_ANIM),
                delay = 2,
                exactMoveDelay = 50,
                faceDir = constants.em_face_south,
                movement = AgilityMovement.ExactMove,
            ),
            AgilityObstacle(
                course = barbarianOutpostCourse,
                step = 2,
                locs = intArrayOf(23144),
                locCoords = setOf(CoordGrid(2550, 3546, 0)),
                level = 35,
                xp = 13.7,
                start = CoordGrid(2551, 3546, 0),
                end = CoordGrid(2541, 3546, 0),
                anim = null,
                delay = 10,
                exactMoveDelay = 0,
                faceDir = constants.em_face_west,
                movement = AgilityMovement.StraightWalk,
            ),
            AgilityObstacle(
                course = barbarianOutpostCourse,
                step = 3,
                locs = intArrayOf(20211),
                level = 35,
                xp = 9.2,
                start = CoordGrid(2538, 3546, 0),
                end = CoordGrid(2536, 3546, 1),
                anim = seq(CLIMB_ANIM),
                delay = 1,
                exactMoveDelay = 0,
                faceDir = constants.em_face_west,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            AgilityObstacle(
                course = barbarianOutpostCourse,
                step = 4,
                locs = intArrayOf(23546, 23547, 23548),
                level = 35,
                xp = 22.0,
                start = CoordGrid(2537, 3547, 1),
                end = CoordGrid(2532, 3546, 1),
                path = listOf(CoordGrid(2532, 3547, 1), CoordGrid(2532, 3546, 1)),
                anim = null,
                delay = 5,
                exactMoveDelay = 0,
                faceDir = constants.em_face_west,
                movement = AgilityMovement.BalanceWalk,
            ),
            AgilityObstacle(
                course = barbarianOutpostCourse,
                step = 5,
                locs = intArrayOf(1948),
                locCoords = setOf(CoordGrid(2536, 3553, 0)),
                level = 35,
                xp = 13.7,
                start = CoordGrid(2535, 3553, 0),
                end = CoordGrid(2537, 3553, 0),
                anim = seq(WALL_CLIMB_ANIM),
                delay = 2,
                exactMoveDelay = 60,
                faceDir = constants.em_face_east,
                movement = AgilityMovement.ExactMove,
            ),
            AgilityObstacle(
                course = barbarianOutpostCourse,
                step = 6,
                locs = intArrayOf(1948),
                locCoords = setOf(CoordGrid(2539, 3553, 0)),
                level = 35,
                xp = 13.7,
                start = CoordGrid(2538, 3553, 0),
                end = CoordGrid(2540, 3553, 0),
                anim = seq(WALL_CLIMB_ANIM),
                delay = 2,
                exactMoveDelay = 60,
                faceDir = constants.em_face_east,
                movement = AgilityMovement.ExactMove,
            ),
            AgilityObstacle(
                course = barbarianOutpostCourse,
                step = 7,
                locs = intArrayOf(1948),
                locCoords = setOf(CoordGrid(2542, 3553, 0)),
                level = 35,
                xp = 13.7,
                start = CoordGrid(2541, 3553, 0),
                end = CoordGrid(2543, 3553, 0),
                anim = seq(WALL_CLIMB_ANIM),
                delay = 2,
                exactMoveDelay = 60,
                faceDir = constants.em_face_east,
                movement = AgilityMovement.ExactMove,
            ),
            AgilityObstacle(
                course = draynorRooftopCourse,
                step = 1,
                locs = intArrayOf(11404),
                level = 10,
                xp = 5.0,
                start = CoordGrid(3103, 3279, 0),
                end = CoordGrid(3102, 3279, 3),
                anim = "seq.human_reachforladder",
                delay = 2,
                exactMoveDelay = 0,
                faceDir = constants.em_face_west,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
            AgilityObstacle(
                course = draynorRooftopCourse,
                step = 2,
                locs = intArrayOf(11405),
                level = 10,
                xp = 8.0,
                start = CoordGrid(3099, 3277, 3),
                end = CoordGrid(3090, 3277, 3),
                path = listOf(CoordGrid(3090, 3277, 3)),
                anim = null,
                delay = 13,
                exactMoveDelay = 0,
                faceDir = constants.em_face_west,
                movement = AgilityMovement.StraightWalk,
            ),
            AgilityObstacle(
                course = draynorRooftopCourse,
                step = 3,
                locs = intArrayOf(11406),
                level = 10,
                xp = 7.0,
                start = CoordGrid(3092, 3276, 3),
                end = CoordGrid(3092, 3267, 3),
                path = listOf(CoordGrid(3092, 3267, 3)),
                anim = null,
                delay = 11,
                exactMoveDelay = 0,
                faceDir = constants.em_face_south,
                movement = AgilityMovement.StraightWalk,
            ),
            AgilityObstacle(
                course = draynorRooftopCourse,
                step = 4,
                locs = intArrayOf(11430),
                level = 10,
                xp = 7.0,
                start = CoordGrid(3089, 3264, 3),
                end = CoordGrid(3088, 3261, 3),
                path = listOf(CoordGrid(3088, 3264, 3), CoordGrid(3088, 3261, 3)),
                anim = null,
                delay = 6,
                exactMoveDelay = 0,
                faceDir = constants.em_face_south,
                movement = AgilityMovement.BalanceWalk,
            ),
            AgilityObstacle(
                course = draynorRooftopCourse,
                step = 5,
                locs = intArrayOf(11630),
                level = 10,
                xp = 10.0,
                start = CoordGrid(3088, 3256, 3),
                end = CoordGrid(3088, 3255, 3),
                anim = seq(JUMP_ANIM),
                delay = 2,
                exactMoveDelay = 45,
                faceDir = constants.em_face_south,
                movement = AgilityMovement.ExactMove,
            ),
            AgilityObstacle(
                course = draynorRooftopCourse,
                step = 6,
                locs = intArrayOf(11631),
                level = 10,
                xp = 4.0,
                start = CoordGrid(3088, 3255, 3),
                end = CoordGrid(3096, 3256, 3),
                anim = seq(JUMP_ANIM),
                waitForArrival = false,
                delay = 3,
                exactMoveDelay = 80,
                faceDir = constants.em_face_east,
                movement = AgilityMovement.ExactMove,
            ),
            AgilityObstacle(
                course = draynorRooftopCourse,
                step = 7,
                locs = intArrayOf(11632),
                level = 10,
                xp = 79.0,
                start = CoordGrid(3096, 3256, 3),
                end = CoordGrid(3103, 3261, 0),
                anim = "seq.human_reachforladder",
                waitForArrival = false,
                delay = 2,
                exactMoveDelay = 0,
                faceDir = constants.em_face_north,
                movement = AgilityMovement.TelejumpAfterDelay,
            ),
        ) + AgilityExtraCourses.obstacles

    val locIds: Set<Int> = obstacles.flatMap { it.locs.asIterable() }.toSet()

    fun findObstacle(locId: Int, coords: CoordGrid): AgilityObstacle? =
        obstacles.firstOrNull { obstacle ->
            locId in obstacle.locs && (obstacle.locCoords.isEmpty() || coords in obstacle.locCoords)
        }

    private fun seq(id: Int): String =
        RSCM.getReverseMapping(RSCMType.SEQ, id) ?: error("Missing agility seq: $id")

    private const val CLIMB_ANIM: Int = 828
    private const val JUMP_ANIM: Int = 2586
    private const val PIPE_ANIM: Int = 749
    private const val ROPE_SWING_ANIM: Int = 751
    private const val WALL_START_ANIM: Int = 753
    private const val WALL_CLIMB_ANIM: Int = 839
}
