package org.rsmod.content.bosses.zulrah

/** Captured phase data consumed by the BossDSL rotation definitions. */
internal object ZulrahRoutineData {
    fun create(): ZulrahRoutine =
        ZulrahRoutine(
            source = "https://rsprox.net/download/3276",
            sourceSha256 = "af6564b8a0c33f9295d4be79554e41701cd3e184c1dc8e8b9bcb706b4fbcf856",
            revision = "234.1",
            mode = "Grid Master",
            startTick = 8318,
            endTick = 520,
            caveat = "Finite recorded branch, not a random rotation generator or proof of normal-world timing.",
            events = listOf(
                ZulrahRoutineEvent(
                    tick = 0,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_ranged",
                    initial = true,
                ),
                ZulrahRoutineEvent(
                    tick = 13,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(2, 1),
                    target = ZulrahPoint(2, -5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 13,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(2, 1),
                    target = ZulrahPoint(5, -5),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    rotation = 3,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 16,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, 1),
                    target = ZulrahPoint(-4, -4),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 3,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 16,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, 1),
                    target = ZulrahPoint(-1, -5),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 19,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(3, 1),
                    target = ZulrahPoint(6, -2),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 2,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 19,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(3, 1),
                    target = ZulrahPoint(6, 1),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 22,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, 2),
                    target = ZulrahPoint(-4, 2),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 2,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 22,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, 2),
                    target = ZulrahPoint(-4, -1),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 10,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 26,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 29,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_magic",
                    x = 10,
                    z = -2,
                ),
                ZulrahRoutineEvent(
                    tick = 32,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(11, -1),
                    target = ZulrahPoint(6, -4),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 35,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(11, 1),
                    target = ZulrahPoint(7, 5),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 38,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, 2),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 41,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, -1),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 45,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(6, 5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 48,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(11, 1),
                    target = ZulrahPoint(6, 5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 51,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 1),
                    target = ZulrahPoint(6, 5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 54,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(11, 1),
                    target = ZulrahPoint(6, 5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 57,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(11, 1),
                    target = ZulrahPoint(6, 5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 60,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(11, 1),
                    target = ZulrahPoint(6, 5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 63,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 66,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_ranged",
                    z = -11,
                ),
                ZulrahRoutineEvent(
                    tick = 70,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(2, -8),
                    target = ZulrahPoint(6, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 73,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(2, -8),
                    target = ZulrahPoint(2, -4),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 76,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(2, -8),
                    target = ZulrahPoint(-1, -3),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 79,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(-4, -4),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 79,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(2, -5),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 82,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(-1, -5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 3,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 82,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(5, -5),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 10,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 86,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 89,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_magic",
                    x = -10,
                    z = -2,
                ),
                ZulrahRoutineEvent(
                    tick = 92,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(-7, 1),
                    target = ZulrahPoint(-3, 3),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 95,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(-3, 0),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 98,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(-7, -1),
                    target = ZulrahPoint(0, -4),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 101,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(3, -4),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 105,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(-3, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 108,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(-3, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 111,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(-3, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 114,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(-3, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 117,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 120,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 123,
                    kind = "tail",
                    symbol = "seq.snakeboss_attack_tail_right",
                ),
                ZulrahRoutineEvent(
                    tick = 130,
                    kind = "tail",
                    symbol = "seq.snakeboss_attack_tail_right",
                ),
                ZulrahRoutineEvent(
                    tick = 138,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, 1),
                    target = ZulrahPoint(-4, -4),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 138,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, 1),
                    target = ZulrahPoint(2, -5),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    rotation = 2,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 141,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(2, 1),
                    target = ZulrahPoint(-1, -5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 141,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(2, 1),
                    target = ZulrahPoint(5, -5),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 10,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 145,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 148,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_ranged",
                    x = 10,
                    z = -2,
                ),
                ZulrahRoutineEvent(
                    tick = 151,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 154,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 157,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 160,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 163,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 166,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_ranged",
                    z = -11,
                ),
                ZulrahRoutineEvent(
                    tick = 169,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(-3, 3),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 172,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(-3, 0),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 175,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(-3, -3),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 178,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(3, -8),
                    target = ZulrahPoint(7, -1),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 181,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(3, -8),
                    target = ZulrahPoint(7, 2),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 184,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(2, -8),
                    target = ZulrahPoint(7, 5),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 188,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(3, -8),
                    target = ZulrahPoint(6, 1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 188,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(3, -8),
                    target = ZulrahPoint(6, 4),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 191,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(3, -8),
                    target = ZulrahPoint(5, -5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 3,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 191,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(3, -8),
                    target = ZulrahPoint(6, -2),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    rotation = 2,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 194,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(2, -8),
                    target = ZulrahPoint(2, -5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 2,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 194,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(2, -8),
                    target = ZulrahPoint(-1, -5),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 10,
                    rotation = 2,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 198,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 201,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_magic",
                    x = -10,
                    z = -2,
                ),
                ZulrahRoutineEvent(
                    tick = 204,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(-2, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 207,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(-2, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 210,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(-2, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 213,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(-2, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 216,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(-2, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 219,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(-7, 1),
                    target = ZulrahPoint(-3, 3),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 222,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(-3, 0),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 225,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(-7, -1),
                    target = ZulrahPoint(-3, -3),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 228,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(-7, -1),
                    target = ZulrahPoint(0, -4),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 10,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 232,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 235,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_ranged",
                ),
                ZulrahRoutineEvent(
                    tick = 238,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(2, 1),
                    target = ZulrahPoint(-2, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 241,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(1, 1),
                    target = ZulrahPoint(-2, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 244,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(1, 1),
                    target = ZulrahPoint(-2, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 247,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(1, 1),
                    target = ZulrahPoint(-2, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 250,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(1, 1),
                    target = ZulrahPoint(-2, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 253,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 256,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 259,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(2, 1),
                    target = ZulrahPoint(-2, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 262,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(1, 1),
                    target = ZulrahPoint(-2, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 265,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(2, 1),
                    target = ZulrahPoint(0, -3),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 268,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(2, 1),
                    target = ZulrahPoint(0, -3),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 271,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(2, 1),
                    target = ZulrahPoint(-4, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 271,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(2, 1),
                    target = ZulrahPoint(-1, -5),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 274,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, 2),
                    target = ZulrahPoint(-4, -4),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 3,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 274,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, 2),
                    target = ZulrahPoint(-4, 2),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 277,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, 1),
                    target = ZulrahPoint(2, -5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 2,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 277,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, 1),
                    target = ZulrahPoint(5, -5),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 10,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 281,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 284,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_ranged",
                    x = 10,
                    z = -2,
                ),
                ZulrahRoutineEvent(
                    tick = 287,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 290,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 293,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 296,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 299,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 302,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 305,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 308,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 311,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 314,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 317,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(1, 2),
                    target = ZulrahPoint(-3, 3),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 320,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(1, 2),
                    target = ZulrahPoint(-3, 0),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 323,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(3, 2),
                    target = ZulrahPoint(7, 2),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 326,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(3, 3),
                    target = ZulrahPoint(7, 5),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 10,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 330,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 333,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_ranged",
                ),
                ZulrahRoutineEvent(
                    tick = 336,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(2, 1),
                    target = ZulrahPoint(8, 1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 339,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(3, 2),
                    target = ZulrahPoint(8, 1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 342,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(3, 2),
                    target = ZulrahPoint(8, 1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 345,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(3, 2),
                    target = ZulrahPoint(8, 1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 348,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(3, 1),
                    target = ZulrahPoint(6, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 352,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(2, 1),
                    target = ZulrahPoint(2, -5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 2,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 352,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(2, 1),
                    target = ZulrahPoint(5, -5),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 355,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, 1),
                    target = ZulrahPoint(-4, -4),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 355,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, 1),
                    target = ZulrahPoint(-1, -5),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 358,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(3, 1),
                    target = ZulrahPoint(6, -2),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 2,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 358,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(3, 1),
                    target = ZulrahPoint(6, 1),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 361,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, 2),
                    target = ZulrahPoint(-4, 2),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 361,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, 2),
                    target = ZulrahPoint(-4, -1),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 10,
                    rotation = 3,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 365,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 368,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 371,
                    kind = "tail",
                    symbol = "seq.snakeboss_attack_tail_right",
                ),
                ZulrahRoutineEvent(
                    tick = 378,
                    kind = "tail",
                    symbol = "seq.snakeboss_attack_tail_left",
                ),
                ZulrahRoutineEvent(
                    tick = 387,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 390,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 393,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(2, 1),
                    target = ZulrahPoint(-2, 5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 396,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(1, 3),
                    target = ZulrahPoint(-2, 5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 399,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(1, 3),
                    target = ZulrahPoint(-2, 5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 402,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(1, 3),
                    target = ZulrahPoint(-2, 3),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 405,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 408,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_ranged",
                    x = -10,
                    z = -2,
                ),
                ZulrahRoutineEvent(
                    tick = 411,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(6, -2),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 411,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(5, -5),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    rotation = 2,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 414,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(6, 1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 414,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(6, 4),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 417,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(2, -5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 417,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(-1, -5),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    rotation = 3,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 421,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(-7, -1),
                    target = ZulrahPoint(0, -4),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 424,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(-7, -1),
                    target = ZulrahPoint(-3, -3),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 427,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(-7, 0),
                    target = ZulrahPoint(-3, 0),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 430,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(-7, 1),
                    target = ZulrahPoint(-3, 3),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 10,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 434,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 437,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_magic",
                    z = -11,
                ),
                ZulrahRoutineEvent(
                    tick = 440,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(2, -8),
                    target = ZulrahPoint(-2, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 443,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(-2, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 446,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(-2, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 449,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(-2, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 452,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_fireball",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(-2, -1),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 455,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(-3, 3),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 458,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(-3, 0),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_magic",
                ),
                ZulrahRoutineEvent(
                    tick = 461,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(-4, -4),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 461,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(1, -8),
                    target = ZulrahPoint(-1, -5),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    rotation = 1,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 464,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(3, -8),
                    target = ZulrahPoint(5, -5),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 3,
                    rotation = 3,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 464,
                    kind = "gas",
                    symbol = "spotanim.snakeboss_double_orb",
                    source = ZulrahPoint(3, -8),
                    target = ZulrahPoint(6, -2),
                    starttime = 45,
                    endtime = 120,
                    angle = 10,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    rotation = 3,
                    cloudLifetime = 30,
                ),
                ZulrahRoutineEvent(
                    tick = 467,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(3, -8),
                    target = ZulrahPoint(7, 2),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 4,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 470,
                    kind = "egg",
                    symbol = "spotanim.snakeboss_egg",
                    source = ZulrahPoint(2, -8),
                    target = ZulrahPoint(7, 5),
                    starttime = 40,
                    endtime = 120,
                    startheight = 370,
                    endheight = 20,
                    impactDelay = 10,
                    spawn = "npc.snakeboss_minion_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 474,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 477,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_melee",
                ),
                ZulrahRoutineEvent(
                    tick = 480,
                    kind = "tail",
                    symbol = "seq.snakeboss_attack_tail_left",
                ),
                ZulrahRoutineEvent(
                    tick = 488,
                    kind = "tail",
                    symbol = "seq.snakeboss_attack_tail_right",
                ),
                ZulrahRoutineEvent(
                    tick = 496,
                    kind = "dive",
                ),
                ZulrahRoutineEvent(
                    tick = 499,
                    kind = "emerge",
                    symbol = "npc.snakeboss_boss_ranged",
                    x = 10,
                    z = -2,
                ),
                ZulrahRoutineEvent(
                    tick = 502,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(8, 4),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 505,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 1),
                    target = ZulrahPoint(8, 2),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 508,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 511,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 514,
                    kind = "attack",
                    symbol = "spotanim.snakeboss_orb",
                    source = ZulrahPoint(11, 0),
                    target = ZulrahPoint(7, 0),
                    starttime = 40,
                    endtime = 90,
                    startheight = 370,
                    endheight = 50,
                ),
                ZulrahRoutineEvent(
                    tick = 517,
                    kind = "dive",
                ),
            ),
        )
}
